### ISSUE TITLE
Καθυστέρηση Αναζήτησης Προϊόντων

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#104]
Στο μενού "Κατάλογος > Προϊόντα" κατά την αναζήτηση, στην εισαγωγή κάθε χαρακτήρα παίρνει περίπου 1 δευτερόλεπτο και φέρνει τα αποτελέσματα. 
Αυτό σημαίνει πως αν πληκτρολογεί κάποιος με κανονική ταχύτητα όλο το SKU "800.1.7" για παράδειγμα, ότι προλάβει να γράψει κατά το loading το διαγράφει και πρέπει να το ξαναγράψει.
Αν αυξηθεί λίγο ο χρόνος που περιμένει μέχρι να κάνει αυτόματη αναζήτηση, το πρόβλημα θα μπορούσε να λυθεί.

**Comment by atsta** [comment]
θα λυθεί με το migration.
