### ISSUE TITLE
New Portal in Preview

### ISSUE THREAD

**Issue by spyroskaravanis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#106]
Please send bugs for new portal here

**Comment by evontas** [comment]
Δεν αποθηκευοται:
**product page:** 
**tab:SEO ->** SEO Title, SEO Description, Meta Title, Meta Description
**tab: Content ->** Στο Additional content, δεν αποθηκεύεται το Description.

**Categories:** 
**Content:** Additional content δεν αποθηκεύεται το Description.
**SEO ->** Meta Description, δεν αποθηκεύεται.

**Collections:** Δεν αποθηκεύεται το Description.

**Customers -> New customer ->** σκάει η σελίδα.
**Store -> Store info ->** σκάει η σελίδα.
**Product settings -> Brands -> New brand ->** δεν σώζει (δεν κάνει τίποτα οταν πατάς save).
**Product settings -> Attribytes ->** To Delete button δεν λειτουργεί μέσα στο singla attribute. Ενώ στη λίστα με τα attributes, αν επιλέξεις ενα και πατήσεις διαγραφή, βγάζει success message αλλά τελκά δεν το διαγράφει.
**Product settings -> Product labels ->** σκάει η σελίδα οταν πατάς New.

Γενικότερα τα περισσότερα Descriptions δεν αποθηκέυονται.

**Γενικό σχόλιο:** on save θα ήθελα να μου εμφανίζει ενα μήνυμα οτι ολοκληρώθηκε επιτυχώς η αποθήκευση.

**Comment by spyroskaravanis** [comment]
> Δεν αποθηκευοται: **product page:** **tab:SEO ->** SEO Title, SEO Description, Meta Title, Meta Description **tab: Content -
**DONE**
>** Στο Additional content, δεν αποθηκεύεται το Description.
**DONE**
> **Categories:** **Content:** Additional content δεν αποθηκεύεται το Description. **SEO ->** Meta Description, δεν αποθηκεύεται.
**DONE**
> **Collections:** Δεν αποθηκεύεται το Description.
**DONE**
> **Customers -> New customer ->** σκάει η σελίδα. **Store -> Store info ->** σκάει η σελίδα. **Product settings -> Brands -> New brand ->** δεν σώζει (δεν κάνει τίποτα οταν πατάς save). **Product settings -> Attribytes ->** To Delete button δεν λειτουργεί μέσα στο singla attribute. Ενώ στη λίστα με τα attributes, αν επιλέξεις ενα και πατήσεις διαγραφή, βγάζει success message αλλά τελκά δεν το διαγράφει. **Product settings -> Product labels ->** σκάει η σελίδα οταν πατάς New.
> 
> Γενικότερα τα περισσότερα Descriptions δεν αποθηκέυονται.
> 
> **Γενικό σχόλιο:** on save θα ήθελα να μου εμφανίζει ενα μήνυμα οτι ολοκληρώθηκε επιτυχώς η αποθήκευση.

**Comment by evontas** [comment]
Στο πλαϊνό μενού, οταν πατάμε πάνω σε ενα sub-menu πχ: catalog -> products, το products δεν ξεχωρίζει κάπως, οτι είναι αυτό που είναι ανοιχτό.

**Comment by atsta** [comment]
> * Στο πλαϊνό μενού, οταν πατάμε πάνω σε ενα sub-menu πχ: catalog -> products, το products δεν ξεχωρίζει κάπως, οτι είναι αυτό που είναι ανοιχτό.
> * Στο footer έχουν μείνει αναφορές & links προς το template Keenthemes -> (About,Support,Purchase) DONE
> * Όταν συμπληρώνω πολλά tabs σε ένα προϊόν (πχ. configurations, attributes, seo) μερικά πεδία δεν αποθηκέυονται. Συγκεκριμένα, στο παράδειγμα μου, τα πεδία του SEO,  δεν αποθηκεύτηκαν. Όταν τα ξαναπέρασα και πάτησα πάλι αποθήκυεση, τα έσωσε.
> * Το ίδιο συμβαίνει και στα collections. Δεν σώζει το tab SEO όταν συμπληρώνω πολλά tabs μαζί.
> * Στη δημιουργία νέας κατηγορίας δεν σώζει το description. Στο edit της κατηγορίας το σώζει.
> * Στη δημιουργία νέου collection δεν σώζει το description, ούτε το seo description. Στο edit τα σώζει.
> * Pricing Rules -> catalog, το Conditions δεν λειτουργεί.
> * Στο μενού, όταν αποθηκέυω κάποιο brand, και μετά κάνω refresh, ενώ παραμένει το brand στο menu, το όνομα του brand το φέρνει κενό.
> * Επίσης δεν δουλευει το delete στο μενού.
> * Πάλι στο menu, στο accordion pages, που επιλέγουμε τις σελίδες που θα προσθέσουμε στο μενού, φέρνει και μερικές εγγραφές με κενό όνομα. Ίσως φέρνει κάποιο draft, ή κάποιο "σκουπίδι" απο τη βάση?

**Comment by spyroskaravanis** [comment]
components translations not working properly

**Comment by Vlefteris92** [comment]
- [ ] Στο δέντρο κατηγοριών εμφανίζεται το "+" ακόμα και όταν δεν υπάρχει άλλο επίπεδο
- [ ] Δεν εμφανίζεται το gauge για τα "out of stock" στο Overview
