### ISSUE TITLE
Sxetakis Media Gallery Counter Error

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#107]
Στον πελάτη Σχετάκης ο counter στο πάνω μέρος της οθόνης του media gallery δείχνει 545 παραπάνω αρχεία και στο μέγεθος το βγάζει -73,69 MB

**Comment by atsta** [comment]
@Vlefteris92 από ότι είδα έχει λυθεί. Λεφτέρη επιβεβαίωσέ το για να το κλείσουμε.

**Comment by Vlefteris92** [comment]
Ναι έχει επιλυθεί.
