### ISSUE TITLE
Collections Error

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#109]
Στην αυτοματοποίηση συλλογών δεν κρατάει τις μεταβλητές μετά την αποθήκευση (πχ τη συγκεκριμένη κατηγορία) και στο πλήθος προϊόντων εμφανίζει αρνητικό.

Ένα παράδειγμα είναι στο Σχετάκης Θεόδωρος ΑΕ

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/a58ed4fe-589f-4f17-ade2-03601e70e1e0)

**Comment by clioli0s** [comment]
Μετά την επιλογή από  το select (πχ την συγκεκριμένη κατηγορία) πρέπει να πατηθεί το κουμπί ✓ που εμφανίζεται δίπλα για να γίνει αποθήκευση της επιλογής

**Comment by Vlefteris92** [comment]
Το έκανα και λειτουργεί κανονικά, μπορεί να κλείσει
