### ISSUE TITLE
Columns στο page Layout Design

### ISSUE THREAD

**Issue by fakelos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#11]
Αν είναι βατό, να υπάρχει δυνατότητα να προσθέσουμε columns έτσι ώστε να μπαίνει ένα component σε κάθε column.

![image](https://user-images.githubusercontent.com/113907624/191019169-5b0d30e9-aa49-47cb-94b2-cca3a7c6f55f.png)

**Comment by spyroskaravanis** [comment]
έχουμε πρόβλεψη για page layouts το οποίο θα υλοποιηθεί σε μετεγενέστερες εκδόσεις. Workarround με custom view.
