### ISSUE TITLE
Folder Delete Error

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#112]
Κατά την προσπάθεια διαγραφής από το media gallery, φακέλων που υπήρχαν πριν το migration σε react κάνει refresh τη σελίδα και δε γίνεται η διαγραφή. Σε νέους φακέλους γίνεται κανονικά.

**Comment by Vlefteris92** [comment]
@clioli0s Πχ στον πελάτη Σχετάκης αν δοκιμάσω να διαγράψω το Root>Products>"Stanley - B&D" που είχε δημιουργηθεί πριν το migration, δεν κάνει τίποτα. Αν φτιάξω ένα νέο φάκελο στην ίδια διαδρομή, τον διαγράφει κανονικά.

**Comment by spyroskaravanis** [comment]
Μήπως το path θέλει url encoding @Panagiotis-Kempas
