### ISSUE TITLE
Home Page Banners Rotation Issue

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#117]
Όταν πας να αλλάξεις τη σειρά στα banners δεν είναι όπως στη προηγούμενη έκδοση, που τα έβαζες με όποια σειρά ήθελες. Υπάρχει κάποιο θέμα. Τα αλλάζει μόνο του με σειρά που δεν θέλω και το πρώτο συγκεκριμένα παρατήρησα πως δε με αφήνει να το αλλάξω (εκεί μάλλον έχει και κάποιο θέμα στο front).

**Comment by clioli0s** [comment]
@KonstantinaTsir σε ποιο component ? Στο hero carousel , στο banner carousel ? Τους αλλάζεις σειρά και δεν αποθηκεύεται ?
