### ISSUE TITLE
Astron Electric category

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#127]
Πελάτης Astron Electric
Να τραβάει τις κατηγορίες από το ITEEXTRA.VARCHAR04 full name category και το X.ITEPPRMS.VARCHAR04:15 category caption

**Comment by spyroskaravanis** [comment]
Πρέπει να υπάρχει διακριτός πίνακας για τις κατηγοριοποιήσεις όσο αφορά το Softone (utbl01, utbl02, utbl03, utbl04, utbl05, mtrcategory, mtrgroup, etc)
