### ISSUE TITLE
Custom Components μερικές φορές δεν εμφανίζονται μπροστά

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#13]
Μερικές φορές όταν επιλέγω custom component, στον οποίο έγιναν ελάχιστες αλλαγές από τον default, δεν εμφανίζονται μπροστά ούτε στο preview. Έκανα και publish theme και συνεχίζει να μην επιστρέφει τίποτα.

![image](https://user-images.githubusercontent.com/113907624/191029336-c5299bcd-6a0e-4e25-b5be-b7da78883ee5.png)

**Comment by spyroskaravanis** [comment]
Για να δούμε αλλαγές στο staging περιβάλλον μπορούμε να βάλουμε στο url ?env=staging. Για παράγειγμα, demo.shopranos.eu?env=staging. Πρέπει πάντα όταν αλλάζουμε script να κάνουμε clear cache (Δεν χρειάζεται στο production το clear cache το χειρίζεται η πλατφόρμα). Αν στα errors της κονσόλας έχουμε ένα vue error που δεν είναι συγκεκριμένο σημαίνει ότι κάτι στο html είναι λάθος (Συνήθως όνομα μεταβλητής με τυπογραφικό ή null exception).
