### ISSUE TITLE
Megamenu issue

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#131]
Πελάτης Βούλγαρης
Στις κατηγορίες του header εμφανίζεται κενό το megamenu

**Comment by spyroskaravanis** [comment]
Μπορείς να βάλεις ένα print screen

**Comment by Vlefteris92** [comment]
Στο mouseover στο megamenu "ΣΚΟΥΛΑΡΙΚΙΑ" εμφανίζεται κενό
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/c2d37e2a-2679-4bbf-8728-a8280affafeb)

**Comment by dveneris1** [comment]
Λευτέρη να σε ρωτησω. Το πρόβλημα είναι ότι έχουν μπεί στο "ΣΚΟΥΛΑΡΙΚΙΑ" και αλλα υπομενού και δεν φαίνονται, ή ότι εχει δηλώθει το "ΣΚΟΥΛΑΡΙΚΙΑ" απλα ως megamenu (χωρις άλλα υπομενού) και φαίνεται το κενό του screenshot;

**Comment by Vlefteris92** [comment]
Όλα τα megamenu στον header φαίνονται κενά, εκτός των brands. Οπότε μήπως δε φέρνει περιεχόμενο.

**Comment by Vlefteris92** [comment]
Μόλις το είδα, όντως όταν το έβαλα με το χέρι ήρθαν κανονικά, νόμιζα πως έπαιρνε αυτόματα τα χαμηλότερα επίπεδα. Κλείνω το θέμα.
