### ISSUE TITLE
Product Detail page

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#132]
Πελάτης Βούλγαρης
Στο προϊόν θέλουν να παίρνουμε από το item.ccctitle τον τίτλο και από το item.cccdescr την περιγραφή

**Comment by spyroskaravanis** [comment]
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/87171031/e6566095-21dd-4032-a720-2a1460f4f5fc)
