### ISSUE TITLE
Availability field

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#139]
Πελάτης Anelysis
Θέλουν να λαμβάνουν την τιμή διαθεσιμότητας από το πεδίο mtrl_cccAtrVal29, θέλουν να φαίνεται στο προϊόν όπως τα brochures κλπ ως link

**Comment by spyroskaravanis** [comment]
Μπορεί να γίνει με προσθήκη custom πεδίου
