### ISSUE TITLE
ReCaptcha issue

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#143]
Anelysis
Στις φόρμες "Ask for Quote" και "Request Registration" όταν ενεργοποιήσαμε το recaptcha έβγαζε σφάλμα.

**Comment by clioli0s** [comment]
Στο Theme Configurator στα settings υπάρχει πεδίο για ReCaptcha Api Key. Έχει συμπληρωθεί αυτό ή εάν υπάρχει είναι σωστό ?
