### ISSUE TITLE
Product SEO issue

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#144]
Anelysis
Στην καρτέλα SEO των προϊόντων στο Shopranos, αν πατήσεις Generate All συμπληρώνει τα πεδία, αλλά μετά από λίγες ώρες χάνεται.

**Comment by atsta** [comment]
@Vlefteris92 το έλεγξα αλλά δε γίνονται clear. το έλεγχουμε λίγο ακόμα και το κλείνουμε.
