### ISSUE TITLE
"Ask for Quote" button reposition

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#145]
Anelysis
Το κουμπί "Ask for Quote" στη σελίδα του είδους να μεταφερθεί από την κορυφή της σελίδας κάτω ή δίπλα από το κουμπί "Add to cart".

**Comment by spyroskaravanis** [comment]
Θα γίνει με το #146. Αν έχει υλοποιηθεί με φόρμα επικοινωνίας τότε χρειάζεται το πακέτο Standard
