### ISSUE TITLE
"Ask for Quote"  form SKU autocomplete

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#146]
Anelysis
Οταν πατηθεί το κουμπί "Ask for Quote" να έρχεται στη φόρμα που ανοίγει το SKU ώστε να μη χρειάζεται να το γράψει ο πελάτης. Ιδανικά θα δημιουργείτο καλάθι που μαζεύει πολλαπλά SKU (παραλλαγή του wishlist) όπως συμβαίνει με πολύ δημοφιλή plugins στο Woocomerce.

**Comment by spyroskaravanis** [comment]
Είναι στο roadmap θα το έχουμε μες τον Σεπτέμβρη
