### ISSUE TITLE
Brochure / Manual / Certificates icons

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#148]
Anelysis
Θα θέλαμε να εμφανιστούν τα παρακάτω εικονίδια στην αρχή της περιγραφής κάθε προϊόντος. 
Και το καθένα να έχει link (σε νέο παράθυρο) που θα το τραβάει από τα παρακάτω πεδία του Softone. Brochure 1: ITEM.cccAtrVal14 / Brochure 2: ITEM.cccAtrVal17 / Manual 1: ITEM.cccAtrVal15 / Manual 2: ITEM.cccAtrVal18 / 
![brochure](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/732d8721-c283-4e25-9b49-dc695404ef49)

**Comment by spyroskaravanis** [comment]
Μπορεί να γίνει στο πακέτο Standard @PolysP
