### ISSUE TITLE
Auto Collection Tag issue

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#150]
Πελάτης Σχετάκης
Βάζει αυτοματοποίηση για μια συλλογή ώστε να δημιουργείται από tag στα προϊόντα αλλά φέρνει άλλα προϊόντα.

**Comment by atsta** [comment]
@Vlefteris92 μπορείς να μας δώσεις ένα παράδειγμα συλλογής που συμβαίνει αυτό;

**Comment by Vlefteris92** [comment]
Στη συλλογή "Πρώτα σε πωλήσεις" βάζει κάποιες συνθήκες και το έχουμε βάλει σε ένα component στην αρχική σελίδα αλλά βγάζει συνέχεια τα ίδια προϊόντα
