### ISSUE TITLE
Category Product list

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#156]
Πελάτης Κλινάκης
Όταν μπεις στη λίστα προϊόντων οποιασδήποτε κατηγορίας χάνεται το τελευταίο δεξιά προϊόν

**Comment by clioli0s** [comment]
@Vlefteris92 Δώσε screenshot αν μπορείς. Πιστεύω ότι δεν χάνεται κάτι απλά έχει να κάνει με το πόσα αποτελέσματα φέρνει ανά page. Θα μπει setting να μπορείς να το αλλάξεις το paging στις λίστες.

**Comment by spyroskaravanis** [comment]
Είναι καθαρά display το page size να διαιρείται με το 3, ακόμη καλύτερα να ορίζει ο πελάτης πόσα θέλει
