### ISSUE TITLE
Categories level

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#163]
Πελάτης Κλινάκης
Όταν κλικάρεις και φέρεις μια κατηγορία από το δεύτερο επίπεδο, σου ανοίγει όλα τα προϊόντα χωρίς να τα κατηγοριοποιεί βάσει του 3ου επιπέδου. 
Το βάζω σαν feature request γιατί θα μας ζητηθεί από πολλούς πελάτες όταν έχουν πάνω από 2 επίπεδα κατηγοριών, θα πρέπει να εμφανίζονται τα προϊόντα μόνο όταν είναι στο τελευταίο επίπεδο κατηγοριών. Αν είναι πιο ψηλά να εμφανίζονται ως κατηγορίες.

**Comment by spyroskaravanis** [comment]
Δυνατότητα επιλογής στην κατηγορία αν θα έρχεται με την category page ή με την category list page
