### ISSUE TITLE
Customer transactions view error

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#166]
Anelysis
Στα transactions του πελάτη στο site όταν πατήσουμε να ανοίξει βγάζει error
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/75da3166-0fd9-492c-9fbf-6fd95dd789df)

**Comment by spyroskaravanis** [comment]
Το πρόβλημα αυτό αφορά το softone και έχει να κάνει με την φόρμα εκτύπωσης που έχει επιλεγεί. Η φόρμα εκτύπωσης μάλλον είναι word η excel και δεν υποστηρίζεται. Πρέπει να φτιαχτεί μία φόρμα εκτύπωσης εσωτερική ή fast report
