### ISSUE TITLE
Hidding filters with no products

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#167]
Πελάτης Σχετάκης
Στο site στα φίλτρα εμφανίζονται κατηγορίες και brands που δεν έχουν προϊόντα, δε θέλουμε να εμφανίζονται όσα είναι μηδενικά

**Comment by spyroskaravanis** [comment]
Εμφανίζονται σύμφωνα με τα best practices
