### ISSUE TITLE
Collection - δεν κάνει save νέο collection

### ISSUE THREAD

**Issue by fakelos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#17]
Προσπαθήσαμε να δημιουργήσουμε collection automation και γίνεται save επ'απείρον και δεν δημιουργείτε.

![image](https://user-images.githubusercontent.com/113907624/191997572-d4496189-d6ae-4428-b089-677ab59fa469.png)

**Comment by spyroskaravanis** [comment]
ναι είναι bug μπορείτε να το προσπεράσετε αν καταχωρίσεται το product count και το sort order
