### ISSUE TITLE
Units In Box

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#171]
Astron Electric
Θέλουν να υπάρχει ένα βήμα πώλησης (να πουλάνε πχ τα καλώδια σε 100αδες μέτρων) και αν γίνεται να παίρνουμε την τιμή από το ITEM.CCCUNITSINBOX

**Comment by spyroskaravanis** [comment]
Θα έπρεπε να χρησιμοποιεί μονάδα μέτρησης πώλησης. Δεν παίζει με το pricing του softone?

**Comment by Vlefteris92** [comment]
Όχι την ποσότητα στο S1 την περνούν οι πωλητές με το χέρι πχ 100-200-300 κλπ μέτρα στα καλώδια
