### ISSUE TITLE
Mini cart / cart page 

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#176]
Πελάτης krannichsolar
Στο mini cart και την σελίδα του καλαθιού βγάζει τα παρακάτω. Η σελίδα του καλαθιού δεν ήταν published και την έκανα μόλις, θέλει κάποια ώρα μήπως ή είναι κάποιο άλλο το πρόβλημα;
![Screenshot 2023-07-12 130708](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/ee1aeba4-ba0b-4bdd-9100-62a0275f0878)
![Screenshot 2023-07-12 130940](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/2ddca2b0-98a9-4983-90e2-58862a184751)

**Comment by spyroskaravanis** [comment]
Δεν έχει δικαίωμα πραγματοποίησης της εργασίας αυτής ο user με τον οποίο κάνει login ο connector του shopranos

**Comment by Vlefteris92** [comment]
Ενημέρωσα, το άλλαξαν και έπαιξε
