### ISSUE TITLE
Product search with spaces

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#177]
Πελάτης Κολάτος
Όταν δεν υπάρχει κενό στο κείμενο αναζήτησης των προϊόντων δεν το εμφανίζει. πχ JF10313

**Comment by atsta** [comment]
@Vlefteris92 δοκιμάζοντας με κενό μπροστά και πίσω, έρχεται αποτέλεσμα. Το ίδιο και από την πλευρά του eshop. Εάν εννοείς κάτι διαφορετικό ή δεν είναι αυτά τα αναμενόμενα αποτελέσματα, συμπλήρωσε με ένα screenshot.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/23361503/0f8bfe7f-4085-4bcd-b7c6-d20ff08363ac)

**Comment by Vlefteris92** [comment]
Αυτό εννοώ, δε θέλει να το κόβει μόνο όταν υπάρχει κενό γιατί λέει πως οι πελάτες τους ξέρουν πχ το 10313 ως κωδικό. Μιλώντας με το Σπύρο την προηγούμενη εβδομάδα είχε σημειώσει να σπάει αριθμούς από χαρακτήρες και να ψάχνει έτσι την αναζήτηση.
