### ISSUE TITLE
Categories level

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#180]
Πελάτης Κλινάκης
Όταν κλικάρεις και φέρεις μια κατηγορία από το δεύτερο επίπεδο, σου ανοίγει όλα τα προϊόντα χωρίς να τα κατηγοριοποιεί βάσει του 3ου επιπέδου.
Το βάζω σαν feature request γιατί θα μας ζητηθεί από πολλούς πελάτες όταν έχουν πάνω από 2 επίπεδα κατηγοριών, θα πρέπει να εμφανίζονται τα προϊόντα μόνο όταν είναι στο τελευταίο επίπεδο κατηγοριών. Αν είναι πιο ψηλά να εμφανίζονται ως κατηγορίες.

**Comment by atsta** [comment]
@Vlefteris92 προστέθηκε. Ενεργοποιώντας το, στην κατηγορία αυτή θα εμφανίζονται οι κατηγορίες-παιδιά και όχι τα προϊόντα της. 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/23361503/faa2702a-ca94-4297-9a4d-3d009f8b7ed9)
