### ISSUE TITLE
Zero prices on catalog

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#182]
Πελάτης Κολάτος
Στον κατάλογο στα προϊόντα εμφανίζει λάθος τιμές. Στο mini cart και το καλάθι φαίνεται κανονικά.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/828c693f-0b4e-4fe0-a651-1f81eb9ea4fc)

**Comment by spyroskaravanis** [comment]
Έχει κλειστό το soft1.
