### ISSUE TITLE
Generate All number of products 

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#185]
Όταν επιλέγουμε συγκεκριμένο αριθμό προϊόντων και πατάμε generate για την περιγραφή, βάζει by default τον αριθμό του συνόλου των προϊόντων εκεί που λέει το πόσα θα επηρεαστούν και όχι μόνο όσα είναι επιλεγμένα.

**Comment by atsta** [comment]
@Vlefteris92 η αυτόματη παραγωγή περιεχομένου (όπως και το export) εφαρμόζεται στα αποτελέσματα της αναζήτησης και όχι στην συγκεκριμένη επιλογή που κάνει ο χρήστης από το grid. Ανάλογα με την περίπτωση, μπορεί να περιορίσει τα αποτελέσματα αναζήτησης μέσω κατάλληλων φίλτρων.
