### ISSUE TITLE
Wrong category alias

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#186]
Dracon IKE
Στις κατηγορίες φέρνει λάθος alias κατά το import
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/4af9ed93-d809-48f7-a251-5427ecf2a415)

**Comment by spyroskaravanis** [comment]
Το alias μπαίνει στην εισαγωγή και μετά δεν αλλάζει αυτόματα.
