### ISSUE TITLE
Να προστεθεί το Swiper API ( swiper js )

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#19]
https://swiperjs.com/swiper-api
Το συγκεκριμένο JS Library, είναι απίστευτα δυνατό και εύχρηστο οσον αφορά οποιοδήποτε slider/swiper.

https://swiperjs.com/demos
Μιας και το shopranos δίνει έμφαση στα custom components, θα ήταν χρήσιμο το swiper js να είναι ήδη included.

**Comment by fakelos** [comment]
Συγκεκριμένα για την vue.
https://swiperjs.com/vue

**Comment by spyroskaravanis** [comment]
@clioli0s

**Comment by spyroskaravanis** [comment]
Για το swipper api προσπαθήσαμε πολύ. Αλλά χρειάζεται node και web pack. 
``` Swiper Vue.js plugin is available only via NPM as a part of the main Swiper library ``` 
https://swiperjs.com/vue
Υπάρχει και η https://github.com/surmon-china/vue-awesome-swiper αλλά είναι depricated και δεν έχει καλή υποστήριξη για vue 3. 
Εναλλακτικά υπάρχει το https://ssense.github.io/vue-carousel/ το οποίο για να λειτουργήσει χρειάζεται τον παρακάτω κώδικα. (Το vue-carousel@2 θα μπορούσε να είναι από τα assets του theme)
```
<script src="https://unpkg.com/@chenfengyuan/vue-carousel@2"></script>
    
<script>
        const emitter = mitt()
        const app = Vue.createApp({});
        app.use(myPlugin);
        app.mixin(globalMixin);
        app.component(VueCarousel.name, VueCarousel);
</script>
```
και μες το component
```
<vue-carousel :data="['Slide 1', 'Slide 2', 'Slide 3']"></vue-carousel>
```

**Comment by spyroskaravanis** [comment]
Επίσης μπορεί να χρησιμοποιηθεί και το swipper api απευθείας από js. Έχουμε μία funtion this._loadScript(src) διαθέσιμη στon κώδικα τον components. Αν χρησιμοποιηθεί θα φορτώσει ένα js και θεωρητικά θα είναι μέσα στο scope της vue γιατί θα φορτωθεί ενώ υπάρχει το instance της vue. Θα επανέλθουμε μετά από ένα τεστ. Πως να φορτώσεις swiper με js στο scope της vue.

**Comment by spyroskaravanis** [comment]
Μπορείτε να βάλετε στο custom layout (Theme Configuration) την βιβλιοθήκη
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>

και στο component να κάνετε initialize τον swiper

```
 mounted() {
        const swiper = new Swiper('.swiper', {
            direction: 'horizontal',
            slidesPerView: 'auto',
            spaceBetween: 30,

            // If we need pagination
            pagination: {
                el: '.swiper-pagination',
                clickable: true
            },
        });
    },
```
