### ISSUE TITLE
Collection manual product imput 

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#191]
Δεν παίρνει πάνω από 23 προϊόντα. Αν βάλουμε 24, βγάζει error. Το κρατάει στο διαχειριστικό αλλά δεν μπορείς να ξανα μπεις σε αυτό.

**Comment by KonstantinaTsir** [comment]
@atsta Έφτιαξα ένα νέο collection με όνομα Lenovo (24/7 added) και εξακολουθεί να υπάρχει θέμα. Μου βγάζει το ίδιο μήνυμα.

**Comment by atsta** [comment]
@KonstantinaTsir το τέσταρα με ένα test collection και μπαίνουν κανονικά. To collection Lenovo δεν το βρήκα. Έχεις κάποιο άλλο που να έχει αυτό το πρόβλημα; Δεν είναι γενικευμένο γι αυτό χρειάζεται να το δούμε εκεί που συμβαίνει.

**Comment by KonstantinaTsir** [comment]
Έχεις δίκιο, συγνώμη. Θες να τσεκάρεις σε αυτό "Fault AOC & Philips", γιατί αυτό ήταν το αρχικό που είχα θέμα και τώρα αν πάω να μπω δεν με αφήνει. Βγάζει "Oops something went wrong!" και σε βάζει να επιστρέψεις στη home page.

**Comment by atsta** [comment]
@KonstantinaTsir λύθηκε.
