### ISSUE TITLE
Order series of identical products

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#195]
Κολάτος
Όταν βάζει παραγγελία διαφορετικά μέτρα από το ίδιο προϊόν θέλουμε να το περνάει στο καλάθι ως διαφορετικά προϊόντα, όχι να αθροίζει τις ποσότητες.

**Comment by atsta** [comment]
@Vlefteris92 έχει προστεθεί.
