### ISSUE TITLE
Pages/Customers/Products etc filter

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#203]
Σε οθόνες όπου εμφανίζεται λίστα αντικειμένων στο διαχειριστικό, όπως είναι η λίστα των Σελίδων ή η λίστα των Προϊόντων, ή η λίστα των Πελατών κλπ γίνεται απευθείας φιλτράρισμα με default όσα είναι σε Active state.
Θα ήταν καλό αν μπορούσε να υπάρχει και η επιλογή (ως default) να μη γίνεται φιλτράρισμα αλλά να φαίνονται όλα τα στοιχεία καθώς αν κάποιος δεν το παρατηρήσει δημιουργούνται ερωτηματικά. Όταν για παράδειγμα κάποιος δημιουργήσει μια νέα σελίδα αυτή μπαίνει by default σε Draft. Όταν θα πάει στις σελίδες αμέσως μετά, η σελίδα που έφτιαξε δεν υπάρχει γιατί το default φιλτράρισμα του φέρνει μόνο τις Active.

**Comment by atsta** [comment]
@Vlefteris92 Λύθηκε.
