### ISSUE TITLE
Category status lookup

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#205]
Κλινάκης
Θέλει να μπορεί να ελέγχεται η κατάσταση (αν θα είναι Active/Draft) των κατηγοριών από το πεδία "Ενεργό Ναι/Όχι" των UTBL

**Comment by atsta** [comment]
@Vlefteris92 μπορεί να φτιάξει στο Softone να ενημερώνεται το πεδίο κατάστασης της παραγγελίας στο onchange του UTLB.

**Comment by spyroskaravanis** [comment]
Θα το φτιάξουμε στο script

**Comment by spyroskaravanis** [comment]
Είναι η default συμπεριφορά
