### ISSUE TITLE
Categories Default Sorting

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#206]
Κλινάκης
Θέλει να υπάρχει default sorting στα Categories

**Comment by atsta** [comment]
@Vlefteris92 η σειρά των κατηγοριών έρχεται με βάση τη δομή του δέντρου κατηγοριών. Εννοείς κάτι διαφορετικό; ποιά είναι η ανάγκη;
