### ISSUE TITLE
Προσθήκη Font Awesome

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#21]
Αν είναι έυκολο να προστεθεί font awesome για την χρήση εικονιδίων fa.

https://fontawesome.com/docs/web/use-with/vue/

**Comment by spyroskaravanis** [comment]
Μπορεί να προστεθεί η font awesome με custom κώδικα. Μπορείτε να κάνετε edit το βασικό html και να βάλετε ότι resources θέλετε. Τα resources μπορείτε να τα ανεβάσετε στο theme assets
![image](https://user-images.githubusercontent.com/87171031/193458265-77e84e1c-6301-4b6e-941a-c9fafeac39e6.png)
