### ISSUE TITLE
Tax Office Problem

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#212]
Πελάτης Βούλγαρης
Δε φέρνει τη ΔΟΥ του πελάτη ενώ φέρνει όλα τα υπόλοιπα στοιχεία.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/d08489b5-c3c4-4054-bd62-da23b89d1e45)

**Comment by dveneris1** [comment]
Λευτέρη ο πελάτης εγινε απο κανένα import? Μηπως δεν έχει δηλωθεί η ΔΟΥ και δεν ερχεται? Γιατι το textbox αποθηκεύει και φερνει κανονικά την ΔΟΥ
