### ISSUE TITLE
Photos Import Issue CY

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#213]
Στο διαχειριστικό στην Κύπρο παρατηρώ το εξής πρόβλημα: 

Κάνω import ένα ZIP, όπως έχουμε πει και πάει και δημιουργεί μόνο του μέσα στο path που θέλω να πέσουν τα jpg φακέλους γα κάθε sku και μέσα εκεί βάζει τις φωτογραφίες. Το είδα γιατί ενώ έκανα import δεν έφερνε μπροστά τις εικόνες την Παρασκευή  28/7.

Έκανα ξανά import τώρα ένα και δεν θα διαγράψω τους φακέλους για να τους δείτε.

Το path είναι το ακόλουθο: root--> products_global--> products_3

**Comment by atsta** [comment]
@KonstantinaTsir λύθηκε.
