### ISSUE TITLE
Customer API Key - Date to section

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#215]
Όταν πας να φτιάξεις ένα νέο Customer API Key, στο section "Date to:" δεν παίρνει ό,τι ημερομηνίες έπαιρνε πριν την "αναβάθμιση" που κάνατε στη πλατφόρμα. Παλιά το βάζαμε να λήγει το 2029 πχ. ενώ τώρα φτάνει μέχρι τις 12/9/23 η ημερομηνία. (Σήμερα: 31/7/23)

![Καταγραφή στο Web_31-7-2023_15713_platform shopranos eu](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/122887554/5e5271a3-5682-4d36-a120-1c3ba668ebc8)

**Comment by dveneris1** [comment]
Η νέα επιλογή για ημερομηνία δείχνει τον τρέχων μήνα Για επιλογή άλλου μήνα και χρονολογίας το date picker έχει 2 βελάκια πάνω πάνω. 

![MicrosoftTeams-image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/87171450/08ea6c11-ccbf-40a7-a32e-25fc6b556480)

**Comment by KonstantinaTsir** [comment]
Τα βελάκια τα βλέπω. Το πρόβλημα μας είναι πως δεν επιλέγει τη μελλοντική ημερομηνία. Πχ 13 Ιουλίου του 2024, αυτό το χρειαζόμαστε για τη παράταση της λήξης του API Key.
