### ISSUE TITLE
Product - Media - Photos

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#218]
Όταν θέλω να αλλάξω σειρά στα αρχεία υπάρχει πρόβλημα. Θυμάμαι πως όταν μεταφέρεις ένα αρχείο αντικαθιστάται η θέση του από το αμέσως προηούμενο αλλά αυτό δεν βολεύει στη διαχείρηση. Μπορείτε να το κάνετε να παίρνει τη σειρά που θέλω χωρίς να κάνει rotate με αυτό τον τρόπο και μόνο του.

**Comment by atsta** [comment]
@KonstantinaTsir η σύνδεση των εικόνων στο προϊόν μέσω της μάσκας, ορίζοντας τη σειρά της στο όνομα της εικόνας θα βόλευε ως λύση;

**Comment by atsta** [comment]
@KonstantinaTsir λύθηκε το πρόβλημα με το rotate στη σειρά των φωτογραφιών.
