### ISSUE TITLE
Error Page όταν πατάς προϊόν στο minicart

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#22]
Πατώντας στο προϊόν στο minicart με οδηγή σε error page. Αυτό γίνεται μόνο στα προϊόντα πατώντας ολοκλήρωση αγοράς συνεχίζει κανονικά και με οδηγεί σε σελίδα για να κάνω login.
![image](https://user-images.githubusercontent.com/113907624/192722057-a487fae7-a9af-4c05-8a62-29c03db2de96.png)

![image](https://user-images.githubusercontent.com/113907624/192721801-cdd4b0b6-183e-4d27-a060-a7527b94e5ca.png)

**Comment by ploumis** [comment]
Πατώντας Back to login page με καθοδηγεί σε σελίδα με slug https://coffeelab.shopranos.eu/Login/Login.
Δηλαδή μπαίνει ενα Login extra και δεν υπάρχει η σελίδα
![image](https://user-images.githubusercontent.com/113907624/192722664-a84f9994-a185-421f-8c37-49b04394cdf0.png)

**Comment by PolysP** [comment]
Λάθος url 
https://kitchenware.shopranos.eu/strongylo-piato-32cm-apo-gyali δεν υπάρχει /product  το σωστό url θα ήταν το παρακάτω

https://kitchenware.shopranos.eu/product/strongylo-piato-32cm-apo-gyali
