### ISSUE TITLE
Cannot delete feeder

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#221]
Σε προσπάθεια να διαγράψω έναν feeder που έφτιαξα, δε γίνεται διαγραφή ούτε από το Actions>Διαγραφή, ούτε από τη διαγραφή επιλεγμένων μετά από μαζική διαγραφή, ούτε μέσα από τον ίδιο τον feeder.

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε
