### ISSUE TITLE
Image dublicate in media gallery

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#223]
Αν ανεβάσουμε την ίδια φωτογραφία (ίδιο αρχείο με ίδιο όνομα) μία φορά ως σκέτο αρχείο και μία φορά μέσω zip, δεν κάνει overwrite αλλά κρατάει και τα 2 αρχεία.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/f2725f4a-0839-489e-b76e-e6945489c0e7)

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε
