### ISSUE TITLE
Edit Category - selection bug

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#224]
Όταν πας να επιλέξεις μία κατηγορία σε 4ο επίπεδο σου κλείνει το δέντρο κατηγοριών αυτόματα. Δεν συμβαίνει το ίδιο με τα υπόλοιπα επίπεδα. (βλ. επισυν. φωτογραφία)

![Καταγραφή στο Web_7-8-2023_11114_platform shopranos eu](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/122887554/0d6fc1c2-0d4e-4066-a18a-5dc7b9540fe4)

**Comment by atsta** [comment]
@KonstantinaTsir λύθηκε.
