### ISSUE TITLE
Related Products Problem

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#226]
Στον πελάτη Kranich (Verus) στην σελίδα του προιόντος δεν εμφανίζονται τα σχετικά προιόντα ενώ έχει δηλωθεί το component και τα συσχετιζόμενα είδη.

**Comment by atsta** [comment]
@AlexandrosStypsianos μας δίνεις ένα παράδειγμα προϊόντος (SKU) της συγκεκριμένης εταιρείας που εμφανίζει αυτό το πρόβλημα;

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε. Απλώς χρειάζεται να περάσεις ξανά τα σχετιζόμενα στα προϊόντα που είχαν για να φανεί η αλλαγή.
