### ISSUE TITLE
Deleting Categories Refresh

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#227]
Κατά την διαγραφή μίας κατηγορίας δεν λειτουργεί σωστά το cache με αποτέλεσμα να συνεχίζει να εμφανίζεται στην λίστα η συγκεκριμένη κατηγορία.
Με εκ νέου log in στην εφαρμογή διορθώνεται.

**Comment by atsta** [comment]
@AlexandrosStypsianos λύηθηκε.
