### ISSUE TITLE
Media gallery upload (eng/gr characters)

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#229]
Όταν γίνεται upload μια φωτγραφίας στο media gallery με κωδικό ο οποίος περιέχει ελληνικούς χαρακτήρες δεν ανεβαίνει.
Στον πελάτη Ζαρμπάνη γίνεται upload αλλα δεν γίνεται σύνδεση και εμφανιζέται η περίγραφη κατα αυτόν τόν τρόπο. (3�2074.png)

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε.
