### ISSUE TITLE
Export Products Error status 400

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#233]
Ζαρμπάνης

Κατά την προσπάθεια εξαγωγής των προϊόντων δεν ολοκληρώνεται. Στο Network βγάζει error status 400

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/5b955632-46e7-4e1f-af71-8f9ddd1229c5)

**Comment by clioli0s** [comment]
@Vlefteris92 υπάρχει bug όταν είναι ενεργό το φίλτρο "'Ολα" που μπήκε πρόσφατα. Αν επιλέξεις άλλο (active, draft κτλ) κάνει export. Θα διορθωθεί
