### ISSUE TITLE
Product number does not show up in "Recently Viewed"

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#237]
Krannich

Στο component « Προϊόντα που επισκεφθήκατε πρόσφατα» μέσα στην σελίδα του είδους, δεν φαίνεται ο κωδικός και η περιγραφή όπως εμφανίζεται στο component «σχετικά προϊόντα». 
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/858a39a5-d211-4da9-9595-896edad772b4)

**Comment by AlexandrosStypsianos** [comment]
Ακριβώς το ίδιο πρόβλημα εμφανίζεται και στον Ζαρμπάνη στο ίδιο component

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε. χρειάζεται update το θέμα.
