### ISSUE TITLE
Custom Feeder Error

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#238]
Στους feeders όταν επιλέγουμε το drop down menu στον custom feeder εναλλάσσει συνεχώς από "Loading" σε "No Options"

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/10094e84-c56a-4092-8f2c-863dbc25703c)
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/1f96cf19-ecf9-4dec-9a00-e11b69a0dd0a)

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε.
