### ISSUE TITLE
Filter problem in Collection with condition (Insert Date)

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#239]
Στις συλλογές με συνθήκη Έυρος ημ/νιας εισαγωγής ,εμφανίζονται τα είδη αλλά τα φίλτρα που έχουμε δηλώσει δεν έχουν στοιχεία.
Το πρόβλημα παρατηρείται  μόνο με την συγκεκριμένη συνθήκη.

![Screenshot 2023-09-04 151308](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/3c7f1823-e3cb-4b94-9ac2-a36ef05d09a7)

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε.
