### ISSUE TITLE
Wishlist Functionality

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#24]
Δεν ξέρω αν έχει υλοποιηθεί wishlist functionality και δεν το βρίσκω από το dashboard, απλώς αν δεν έχει υλοποιηθεί αν είναι δυνατόν να προστεθεί.

**Comment by atsta** [comment]
υπάρχει το functionality ως shopping lists στο οποίο έχετε πρόσβαση μετά το login.

**Comment by spyroskaravanis** [comment]
![image](https://user-images.githubusercontent.com/87171031/193423263-6b9d8d50-6e78-4827-9345-b2ba62809103.png)

![image](https://user-images.githubusercontent.com/87171031/193423307-8f2ff425-abff-4362-baed-d55f963e64da.png)
