### ISSUE TITLE
Cart problem when specific product added

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#242]
Ζαρμπάνης

Εμφανίζεται πρόβλημα στο καλάθι και δε φαίνονται τα προϊόντα όταν γίνεται προσθήκη το 022011000066
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/0529e96a-7756-40ac-9e09-8a64c7a6d8d3)
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/4b493d20-438a-4c3d-b444-5832359cd207)

Σε προσθήκη άλλου προϊόντος όπως το 052000000096 εμφανίζεται κανονικά.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/89e789e5-9a51-4958-ba82-91dbac8706a0)

Έχει δοκιμαστεί με πώληση εκτός αποθέματος και στα δύο προϊόντα και στο γενικό και εισαγωγή όλων των προϊόντων μετά από κάθε αλλαγή.

**Comment by AlexandrosStypsianos** [comment]
Παρουσιάστηκε το συγκεκριμένο πρόβλημα με το καλάθι και σε αλλους κωδικούς .Τα είδη αυτά έχουν κανονικά φωτογραφίες συνδεδεμένες και φαίνονται κανονικά και στη σελίδα. 


![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/e92cbacd-865e-45de-8c2b-fa13de2f4b1a)



![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/e1b237e2-c2ed-4510-8ed9-d6bbaf5e4d33)
