### ISSUE TITLE
Klinakis - Collection page problem

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#244]
Όταν πάμε να μπούμε στη συλλογή "Προσφορές" βγάζει error.
Σε νέα συλλογή ανοίγει κανονικά.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/d4bf8b3f-1588-4198-a135-2319af4cbc31)

**Comment by Vlefteris92** [comment]
Το ίδιο και στον Σχετάκη
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/e1558734-7d2f-4dc3-aaf2-1bcf06983b3e)

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε.
