### ISSUE TITLE
Fixed header menu

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#246]
Όταν επιλέγω Fixed header menu δε φαίνονται τα στοιχεία του μενού στο layoutB
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/f03c1bcf-8aa3-4fae-be10-9d8ec1b61d61)
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/8b0f9e2c-c29b-4caa-8f4a-1ed459481e62)

**Comment by clioli0s** [comment]
Οταν επιλέγουμε Fixed Header δεν δουλεύει σωστά το ύψος εάν υπάρχει και topbar. Θα πρέπει να βγει το topbar ή να το δούμε κατά περίπτωση
