### ISSUE TITLE
Add-to-cart number allign problem

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#248]
Ζαρμπάνης
Δεν εμφανίζονται σωστά οι ποσότητες για προσθήκη στο καλάθι
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/153a723a-178c-41f1-9281-4d838353552c)

**Comment by clioli0s** [comment]
Διορθώθηκε σε καινούρια έκδοση του θέματος
