### ISSUE TITLE
LayoutB sign-in problem

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#250]
Όταν επιλέγεται το LayoutB δε δίνεται η δυνατότητα να κάνει login ο χρήστης
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/d5c4184e-6bc7-463d-975c-963bd4a29612)

**Comment by clioli0s** [comment]
Διορθώθηκε με καινούρια έκδοση θέματος
