### ISSUE TITLE
Product Description default table

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#253]
Στην περιγραφή προϊόντος στον default πίνακα υπάρχει αναγραμματισμός στο mtrl σε mrtl.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/128ec7bc-502f-4aed-9661-825b341ebe7b)

**Comment by Vlefteris92** [comment]
Επίσης το default πεδίο είναι το mtrl.remarks

**Comment by atsta** [comment]
@Vlefteris92 Λύθηκε.
