### ISSUE TITLE
Checkout user permission 

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#256]
Greenbay

Στο επίπεδο του checkout δεν υπολογίζονται τα δικαιώματα που έχουν δοθεί στο χρήστη. 
Σε ρόλο πελάτη που έχω φτιάξει που δεν έχει το display prices δε φαίνονται οι τιμές σε κατάλογο και καλάθι, φαίνονται όμως κανονικά στο checkout

**Comment by spyroskaravanis** [comment]
ισχύει?

**Comment by Vlefteris92** [comment]
@spyroskaravanis Ναι ισχύει ακόμα

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/3ab3ae0c-cfe2-455e-ae98-dd84e88ddc85)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/a34b3e01-b4ab-4e3e-8541-8cf007705feb)

**Comment by dikoutas** [comment]
και Ζαμπέλης
