### ISSUE TITLE
Setting for showing discount or not on catalog

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#259]
Greenbay

Θα πρέπει να υπάρχει επιλογή για το αν θα φαίνεται στον κατάλογο με σβήσιμο η τιμή χονδρικής και η έκπτωση για τον πελάτη.

**Comment by spyroskaravanis** [comment]
Για τον πελάτη έγινε αλλαγή. Για το setting θα το δούμε στο μέλλον
