### ISSUE TITLE
Order with specific steps of QTY

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#260]
Πελατης Ζαρμπανης
 Βαζει βήμα παρραγγελίας και  εχει προβλημα οταν βάζει χειροκίνητα  ποσοτητα.
Πχ. προιόν με βήμα 4 και θέλω να δώσω 20 τεμαχια  οταν πατάω το 2 μου μηδενίζει γιατι δεν ειναι στο βημα 4.
αν πατήσω το 7 μου το κάνει 4 κλπ..

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε.
