### ISSUE TITLE
LayoutB Logo too small

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#265]
Βούλγαρης

Το μέγεθος του logo στο LayoutB είναι μόνιμα σταθερό και πολύ μικρό. Θα πρέπει να παίρνει το μέγεθος της εικόνας όπως γίνεται στο LayoutA

**Comment by atsta** [comment]
@Vlefteris92 Λύθηκε.
