### ISSUE TITLE
Text with Image text-muted 

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#266]
Βούλγαρης

Στο component Text With Image το κείμενο παίρνει την ιδιότητα text-muted στην html και βγάζει το κείμενο σα να είναι πιο ανοικτό χρώμα.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/951eb5a9-fb92-4c53-9d9f-466cd4f94e1f)

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε με css.
