### ISSUE TITLE
Email profile templates show up

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#267]
Θα ήταν καλό να φαίνεται κάπου (έστω και με mouse over) το body των mail templates ώστε να γνωρίζουν οι πελάτες ποιο επιλέγουν. 

Προς το παρόν το έχουν ζητήσει από Βούλγαρη και Κλινάκη

**Comment by spyroskaravanis** [comment]
Να περαστεί από φανή
