### ISSUE TITLE
Pagination στο Filters Component

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#27]
Δεν ξέρω κατά πόσο είναι λογικό να υπάρχει το grid μέσα στο filters component, αλλά κατά τ'άλλα παρατήρησα μερικά λαθάκια.
1ον δεν υπάρχει μεταβλητή products και το showPagination θα πρέπει το show να είναι με κεφαλαίο S για να εμφανιστεί εξαρχής το pagination.
![image](https://user-images.githubusercontent.com/113907624/193045471-552c0643-0fc1-4e76-b886-f06e2b56f5d4.png)

Επιπλέον, μπροστά η 3η σελίδα εμφανίζεται ως 2.55 και τα κουμπιά δεν είναι clickable, τα functions που καλουν δεν υπάρχουν.
![image](https://user-images.githubusercontent.com/113907624/193046962-d5afc1a4-b906-40cf-9aaa-c38e106a3c09.png)

**Comment by spyroskaravanis** [comment]
Ναι μπορεί το grid να μην είναι απαραίτητο. Το αφήνουμε στο default προς το παρόν και βλέπουμε.
