### ISSUE TITLE
Order report changes /  year 2023

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#271]
Πελάτης Green Bay

Στη αναφορά παραστατικών δεν θέλει να βλέπει τα πραστατικά  κιβωτίων. 
Επίσης η αναφορά να υπολογίζει μονο την τρέχουσα χρήση.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/bc753e43-9679-49b6-b0e4-28d3bba83c9d)

**Comment by spyroskaravanis** [comment]
Να ρυθμιστεί στο ERP να μένει ο κωδικός παραστατικού ή να φτιαχτεί άλλη σειρά αν δεν θέλουν να πειραχτεί η υφιστάμενη
