### ISSUE TITLE
Cannot change connector settings

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#272]
Όταν έχει δημιουργηθεί ένας connector και προσπαθήσω να κάνω αλλαγή των στοιχείων του δε γίνεται η αποθήκευση.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/05e14805-57c0-42dc-97c1-6f63791e21f3)

**Comment by atsta** [comment]
@Vlefteris92 αν δεν εχει ενεργοποιήσει το λογαριασμό 955 στο s1 δεν μπορεί να το αλλάξει γιατί αλλάζουμε τις παραμέτρους κάνοντας Login στο s1. Στη συγκεκριμένη περίπτωση αποτυγχάνει γιατί δεν είναι σωστά σεταρισμένος ο λογαριασμός.
