### ISSUE TITLE
Discounts appear as 0 on .pdf

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#275]
Κλινάκης

Στο pdf της παραγγελίας εμφανίζονται μηδενικές εκπτώσεις παρόλο που στην παραγγελία υπάρχει έκπτωση.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/5273bb4f-a873-415b-bd9c-5098d8ad98bf)

**Comment by atsta** [comment]
@Vlefteris92 αναμένουμε παραγγελία με μη μηδενική έκπτωση

**Comment by Vlefteris92** [comment]
Όλες οι παραγγελίες μου ανέφεραν πως έχουν μη μηδενικές εκπτώσεις καθώς εφαρμόζονται τιμολογιακές πολιτικές στου πελάτες
