### ISSUE TITLE
Email order template

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#276]
Υπάρχει ένας λάθος τονισμός στο μέιλ που στέλνεται στο default Email order template
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/14362c61-4463-4bae-8b81-5a7e54718b6f)

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε
