### ISSUE TITLE
Product Details σελίδα δεν εμφανίζει τα components

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#28]
Παρόλο που πρόσφατα δούλευα στην σελίδα προϊόντος και δούλευε κανονικά, τώρα δεν εμφανίζει τα components ακόμα και σε env=staging.

![image](https://user-images.githubusercontent.com/113907624/193267191-7f241545-df4d-415d-a092-6bfb0cfeee91.png)
![image](https://user-images.githubusercontent.com/113907624/193267397-a1bbb3dc-ed0b-48a5-aa37-e91f4d848390.png)

![image](https://user-images.githubusercontent.com/113907624/193267278-33730876-067e-4b5d-8220-ab44d6dc6f6f.png)

**Comment by clioli0s** [comment]
@ploumis υπάρχει λάθος έλεχγος  στο custom Component του Product Single
![image](https://user-images.githubusercontent.com/94973119/193281600-950e2293-1e56-4bba-abbd-7a494b666c59.png)
Το tags ειναι null , χρειάζεται και έλεγχος για nullability πάνω στα tags.

**Comment by spyroskaravanis** [comment]
Ένας γρήγορος τρόπος για να δεις αν είναι πρόβλημα της πλατφόρμας είναι να κάνεις validate με την default προβολή.
