### ISSUE TITLE
Scroll to top when clicking on menu

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#281]
Κλινάκης

Θέλει να μην ανεβαίνει στο πάνω μέρος της σελίδας όταν κλικάρει σε κάποια κατηγορία από το μενού αριστερά (LayoutB)

**Comment by atsta** [comment]
Keep subcategories open upon selection

**Comment by Vlefteris92** [comment]
Μπορούμε να το δούμε αυτό; Είχαμε ενημερώσει πως θα έκλεινε 20/10
