### ISSUE TITLE
Media Gallery GTIN Mask Problem 

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#282]
Πελάτης Mega Electrics 

Κατα το upload των φωτογραφιών των ειδών δεν γίνεται συγχρονισμός με τα είδη.
Η μάσκα που δηλώνει ειναι με το barcode (GTIN).Συγκεκριμένα δηλώνει το GXNNN. 
Εγινε δοκιμή  μονο με το Barcode  mask:(G)  και πάλι παρυσιάζει πρόβλημα. 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/b4fdc274-0671-4297-9902-236f83cc3192)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/0fef76bf-bfbf-4774-aec1-0911de972c73)

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε.
