### ISSUE TITLE
Μηνύματα Functionality σε πελάτες

### ISSUE THREAD

**Issue by fakelos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#284]
Θέλουμε για τα B2B κυρίως να υπάρχει λειτουργικότητα μηνυμάτων.

Ουσιαστικά, να γίνεται σε όλους τους πελάτες να στέλνεται ένα μήνυμα που θα βλέπουν στον λογαριασμό τους. Όταν έχουν αδιάβαστο μήνυμα να εμφανίζεται μια κόκκινη βουλίτσα όπως στην εικόνα 1 (image001). Έπειτα στον λογαριασμό τους να έχει ένα tab στο οποίο θα έχει επίσης την βουλίτσα αν υπάρχουν αδιάβαστα μηνύματα.

Στο tab αυτό θα εμφανίζονται με χρονολογική σειρά τα μηνύματα αυτά, και θα είναι με bold αν δεν έχουν διαβαστεί. Όταν πατήσουν πάνω ή το ανοίξουν(έστω ότι είναι accordion) τότε αλλάζει το font-weight σε κανονικό και δεν θα εμφανίζεται η βουλίτσα(εφόσον δεν υπάρχει κάποιο αδιάβαστο).

![image001](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/132381305/bab3b017-e711-42e7-b9ea-a1a213ae59ae)
![image002](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/132381305/6766bdee-d46d-4627-8774-e8cdeed78ae3)
![image003](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/132381305/b253143b-0e77-4f74-a9ac-22d78ba828b5)

**Comment by atsta** [comment]
@fakelos Θα ενσωματωθεί η λειτουργία των ανακοινώσεων σε πελάτες σε επόμενες εκδόσεις.
