### ISSUE TITLE
Filter Problem (BIO) Brand List 

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#287]
Πελάτης Green Bay

Οταν επιλέγω συγκεκιρμένα Brands στη σελίδα, δεν εμφανίζεται σωστα το φιλτρο "Χαρακτηριστικά". 
Το χαρακτηριστικό ΒΙΟ εμφανίζεται εξω απο τη λίστα. 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/e11be643-55d2-40d9-8b62-a21f12614385)

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε.
