### ISSUE TITLE
Change comment field in order (Atlantis)

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#290]
Πελάτης Green Bay 

Χρειάζεται αλλαγή του πεδίου που ερχονται τα σχολια της παραγγελίας στο ERP.
Απο το πέδιο FINTRADE Data Field: JUSTIFICATION
θέλει να εμφανίζεται στο STORETRADE Data Field: SECJUSTIFICATION.

**Comment by atsta** [comment]
@AlexandrosStypsianos Λύθηκε.
