### ISSUE TITLE
##Add to Cart##

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#291]
Πελάτης Ζαρμάνης

Στις λίστες ειδών η προσθηκη στο καλάθι εμφανίζεται με τη παρακάτω μορφή.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/4f5e116f-fa3a-4c76-87b5-ed59571f55f7)

**Comment by atsta** [comment]
@AlexandrosStypsianos κάνε update to theme. Έχει λυθεί.
