### ISSUE TITLE
Additional cookies 

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#292]
Στα πρόσθετα cookies δεν εμφανίζεται ποια είναι όταν πατάς το βελάκι.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/9840ee07-aaa7-4cfe-af7f-bcf1cec308e3)

**Comment by dveneris1** [comment]
@Vlefteris92 Δοκιμαστε μεσα στο cookie block να σβισετε το row 
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/87171450/4052e506-ee8f-4cd2-a0d2-cdc6c53380e7)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/87171450/8c8fe4d5-975d-4052-a802-256b7619d880)
