### ISSUE TITLE
Media Gallery Issue

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#296]
Δεν ανεβαίνουν files. Ανεβαίνουν μόνο zip-άκια.

**Comment by atsta** [comment]
@KonstantinaTsir έκανα ένα τεστ και φαίνεται να ανεβαίνουν κανονικά αρχεία. Μπορείς να μας δώσεις ένα παράδειγμα φακέλου και αρχείου που προσπάθησες να ανεβάσεις και απέτυχε;

**Comment by KonstantinaTsir** [comment]
Σήμερα που ανέβασα ένα άλλο αρχείο στο ίδιο path ήταν οκ. Σε ευχαρίστω πολύ Αθηνά.

Ανέβασα jpg και το path ήταν: Root-->New Category Images-->TECHNOLOGY-->Components-->new Comp
