### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#297]
Θα ήθελα αν είναι εφικτό το modal να μπορεί να γίνει drag & drop, όπου επιθυμεί ο διαχειριστής (θα βοηθούσε στην επεξεργασία όγκου κωδικών).

**Comment by atsta** [comment]
@KonstantinaTsir έχουμε τη δυνατότητα μαζικής επεξεργασίας προϊόντων. Εννοείς κάτι διαφορετικό; 
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/23361503/6fdb4380-b113-46e9-9bf0-7e75691096fe)
