### ISSUE TITLE
Price / <per> Unit

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#298]
Πελατης Krannich.

Υπάρχει η ανάγκη στην εμφάνιση των τιμών να αφαιρεθεί η λέξη <Ανά >. 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/63d19107-ed59-4df1-8e1b-59e6be26ec04)

**Comment by atsta** [comment]
@AlexandrosStypsianos έχει λυθεί σε νέα έκδοση του θέματος
