### ISSUE TITLE
Product Template για catalog, related etc

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#30]
Αν είναι δυνατό, να υπάρχει ένα single product template το οποίο δημιουργούμε, το οποίο μετά καλείτε όπου θέλουμε( catalog ,related , products block etc)

**Comment by spyroskaravanis** [comment]
@clioli0s Θα ήταν ωραίο να έχουμε global (html) templates στα οποία να δηλώνουμε για ποια components παίζουν

**Comment by spyroskaravanis** [comment]
Φτιάξαμε τα reusables
