### ISSUE TITLE
Cannot load image on catalog

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#305]
Μαζιώτης

Σε μερικά είδη (πχ ΖΑΓ.0002 & ΖΑΓ.0008) ενώ φαίνεται η φωτογραφία στο product page, δε φαίνεται στον κατάλογο.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/2622aba4-7ef5-492b-864b-e607c67d6c7f)
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/d7c15cc9-f656-4339-9af4-0d5fc90dc0dc)

**Comment by atsta** [comment]
@Vlefteris92 είχαμε κασαρει τα αποτελέσματα. εκανα μία αλλαγή και φαίνεται τώρα κανονικά.
