### ISSUE TITLE
Αdditional content - Link

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#310]
Θα ήταν ωραίο να μπορεί στο μέλλον ο διαχειριστής να προσθέτει και εδώ link. Σαν εσωτερικό promo σε κάποια σελίδα.

**Comment by atsta** [comment]
@KonstantinaTsir Μπορεί να προσθεθεί link στο κομμάτι της περιγραφής 
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/23361503/097645e5-0348-41d0-93d8-038a4d3df50f)

**Comment by KonstantinaTsir** [comment]
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/122887554/7f6e567e-0a5a-4617-beb1-69f2ce58b976)


@atsta Έκανα αυτό που μου είπες αλλά δεν ήθελα αυτό. Θα ήθελα το εσωτερικό αυτό image να έχει link πίσω του. 
Όπως ακριβώς λειτουργούν και τα banners της Home Page.
