### ISSUE TITLE
Scroll-to-Top / Chat icon overlap

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#312]
Το εικονίδιο του chatbot και το Scroll-to-Top πέφτουν το ένα πάνω στο άλλο.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/e4f10b11-977b-43b4-a207-715d80d71e41)

**Comment by atsta** [comment]
@Vlefteris92 Λύθηκε.
