### ISSUE TITLE
Filter customers by category

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#314]
Σχετάκης

Ζητά να μπορεί να φιλτράρει τους πελάτες στο διαχειριστικό βάσει της κατηγορίας τους.

**Comment by atsta** [comment]
@Vlefteris92 τα customer groups προς το παρόν χρησιμεύουν ως πεδίο ομαδοποίησης των πελατών για εφαρμογή τιμολογιακών πολιτικών
