### ISSUE TITLE
 Preview Problem on Product Component (Per Unit)

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#315]
Υπάρχει πρόβλημα στα component  που εμφανίζουν είδη πχ (Products Block, Last visited products,Banner with products carousel).
Δεν εμφανίζεται η μονάδα μέτρησης σε όποια σελίδα και αν υπάρχουν τα component. 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/cec97440-3478-4bde-b999-54273d5347d2)

**Comment by atsta** [comment]
@AlexandrosStypsianos Λύθηκε (update theme)
