### ISSUE TITLE
Deafult no Image Grouping

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#318]
Ζητηθηκε απο πελάτη Σε είδη που δεν υπάρχουν φωτογραφίες να εχει την δυνατότητα να βαλει μια κοινή φωτογραφία αλλα για συγκεκριμενη ομάδα ειδών πχ ανα Brand.

**Comment by Vlefteris92** [comment]
Το παραπάνω έχει ζητηθεί από αρκετούς πελάτες

**Comment by dikoutas** [comment]
Ανάλυση αρκετή και ένα sprint δουλειά.

**Comment by spyroskaravanis** [comment]
Να περαστεί από φανή
