### ISSUE TITLE
Delete Foto Problem

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#319]
Κατα την διαγραφή φωτογραφίας απο συλλογή η κατηγορία με την αποθήκευση ξανα εμφανιζεατι η φωτογραφία. 

Πελάτες για δοκιμή : ΠΑΠΑΠΟΣΤΟΛΟΥ , ΣΚΟΡΔΑΚΗΣ, ACCESS

**Comment by Vlefteris92** [comment]
Παράδειγμα Παπαποστόλου
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/a4b06541-e24b-4a17-a04b-2f2af3294a37)
