### ISSUE TITLE
Το Categories List δημιουργεί errors

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#32]
![image](https://user-images.githubusercontent.com/113907624/195334687-37b6bcd5-73ff-46b4-bdaa-cbc828b115af.png)

**Comment by spyroskaravanis** [comment]
Ναι, δεν είναι global component αφορά την σελίδα (https://coffeelab.shopranos.eu/categories) και μπορεί να πάρει και το alias της Κατηγορίας (https://coffeelab.shopranos.eu/categories/espresso-bar) ώστε να δείξει τις υποκατηγορίες της κατηγορίας. Οπότε διορθώθηκε το να μην είναι global. Αν θέλουμε ένα component στο οποίο να δείχνουμε κατηγορίες σε οποιαδήποτε σελίδα να βάλουμε ένα νέο θέμα στο οποίο να λέμε γιατί το θέλουμε. Επίσης, Θα δώσουμε μία συνάρτηση με την οποία θα μπορούμε να φέρουμε κατηγορίες σε υφιστάμενο component από JS.
