### ISSUE TITLE
Category tree mismatch

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#320]
Βασιλάκης, Μαζιώτης

Οι κατηγορίες δεν ακολουθούν το δέντρο του διαχειριστικού

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/b5e0e545-7eb5-4685-a350-5fa90db9acaf)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/05f69186-7aea-40ee-a52e-4bdd7b5b131d)

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε
