### ISSUE TITLE
Order from excel with MPN

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#321]
Κατα την εισαγωγή παραγγελίας απο excel με MPN εμφανιζεται μηνυμα οτι δεν βρεθηκαν τα είδη.  Παρολαυτα η εισαγωγη των ειδών γίνεται κανονικά. 
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/552ebf05-1068-49e1-ae1f-5212bfc5d5f9)

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε
