### ISSUE TITLE
Orders Sync Problem

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#323]
Κατά την αλλαγή της καταστασης παραγγελίας και της αλλαγης στις ποσότητες  σε μια ORD  στο ERP  δεν ενημερώνεται το Shopranos. 
Επειτα απο διαγραφή της παραγγελίας στο Shopranos  και με εκ νεου manual import ερχονται σωστα οι αλλαγές.

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε (παρακαλουθήστε το και με τους πελάτες που είχαν το πρόβλημα)
