### ISSUE TITLE
Description column in product list

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#325]
Βασιλάκης

Ζητά στη λίστα των προϊόντων στο διαχειριστικό να υπάρχει στήλη με την περιγραφή

**Comment by atsta** [comment]
@Vlefteris92 προσεχώς στο grid θα μπορεί ο διαχειριστής να επιλέξει ποιες στήλες θέλει να βλέπει, σε ποια σειρά, με ποιο μέγεθος κτλ.
