### ISSUE TITLE
Empty filters when selected by breadcrump

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#328]
Euronics

Εμφανίζονται φίλτρα χωρίς κανένα αποτέλεσμα όταν πηγαίνουμε από το breadcrump ενώ όταν πάμε από το μενού εμφανίζονται κανονικά.

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε (update theme)
