### ISSUE TITLE
Client Profile Tab Invoices (date add)

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#329]
Στο προφίλ του πελάτη στο tab καρτέλα για να εμφανιστούν τα αποτελέσματα χρειάζεται ο χρήστης να συμπληρώνει την ημ/νια -ΕΩΣ- . Σε διαφορετική περίπτωση εμφανίζει κενά και ο πελατης νομίζει οτι προκειται για λάθος. 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/cf6b53ba-9ec9-4316-ba16-463223d8ef59)

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε (update theme)
