### ISSUE TITLE
Products block  / Units Problem

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#332]
Στο component Products Block  δεν εμφανίζονται οι μονάδες μέτρησης.

 
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/21b6d798-9084-4252-b4c4-a73fccc61a79)

**Comment by spyroskaravanis** [comment]
Ισχύει ακόμα?

**Comment by AlexandrosStypsianos** [comment]
Έπειτα απο έλεγχο συνεχίζει να μην φέρνει μονάδες μέτρησης.

Με εκτίμηση,
Alexandros Stypsianos
Digital Commerce Consultant | Digital Commerce & CX BU
E: ***@***.******@***.***>

T: +30 215-5517050
L. Amfitheas 11, 17122, Athens, Greece
www.softone.gr<http://www.softone.gr/>
***@***.***

[facebook]<https://www.facebook.com/SoftOneTechnologies>
[linked in]<http://www.linkedin.com/company/softone-technologies-s-a->
[twitter]<http://twitter.com/soft_one>
[youtube]<http://www.youtube.com/SoftoneTechnologies>
________________________________
This email and all attachments are confidential and are intended solely for use by the individual to whom this email is addressed unless otherwise noted. If you are not the named addressee you should not use, print, disclose, distribute or copy this e-mail or take any action in reliance on its contents. Any views, opinions and content expressed or contained herein are solely those of the sender and do not necessarily represent SoftOne Technologies S.A. nor conclude any binding agreement on behalf of SoftOne Technologies S.A. | 8 Achilleos & L. Katsoni Str., 176 74, Kallithea
