### ISSUE TITLE
XML Objects

### ISSUE THREAD

**Issue by tpolitis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#334]
Να προστεθεί η πληροφορία και για τα υπόλοιπα objects τα οποία αφορούν τον κατάλογο όπως brands, categories, κλπ...
(Δηλαδή να μπορούμε να κάνουμε access την πληροφορία για όλα categories όπως κάνουμε και για τα products)

**Comment by atsta** [comment]
@tpolitis ολόκληρα τα objects για το brand, category, unit που υπάρχουν πάνω στο προϊόν βρίσκονται στα properties category και categoryObj, brand και brandObj, unit και unitObj πάνω στο παραγώμενο feed.
