### ISSUE TITLE
Change Shiping Address on pdf order

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#337]
Κατά την χειροκίνητη αλλάγη της διευθυνσής αποστολής στο chekout στο pdf  που παράγουμε εμφανίζεται η  default  διευθυνση του πελάτη στα στοίχεια διακίνησης. 

 
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/d58a957d-82a4-4d95-80de-188414e26c0c)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/e918b29d-93f3-400d-b1c0-0f447faf21e2)

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε.
