### ISSUE TITLE
Product PDF Issue

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#338]
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/122887554/9d5cefdb-52e4-41dc-a2c1-e0ade73cf783)

Όταν πατάμε στην προβολή pdf σε ένα προϊόν στο site, μας βγάζει το παραπανω μήνυμα. 

https://[media.shopranos.eu/media/919c99f4-412f-483e-8dcc-d8225bd4e41d/33e4a246-e7e1-43f0-b74f-bb0ea5e1c05a/33e4a246-e7e1-43f0-b74f-bb0ea5e1c05a?1701406852.1068525](https://media.shopranos.eu/media/919c99f4-412f-483e-8dcc-d8225bd4e41d/33e4a246-e7e1-43f0-b74f-bb0ea5e1c05a/33e4a246-e7e1-43f0-b74f-bb0ea5e1c05a?1701406852.1068525)

Κοιτώντας το media gallery, παρατηρούμε ότι το αρχείο  υπάρχει 3 φορές (όχι σε όλους τους κωδικούς) αλλά κανένα από τα 3 links δεν συμπίπτει με το παραπάνω link του error.

**Comment by atsta** [comment]
@KonstantinaTsir θα μπορούσες να μας πεις ένα προϊόν που να έχει pdf στο site και έχει αυτό το πρόβλημα;

**Comment by KonstantinaTsir** [comment]
Το ακόλουθο: 

**00135409**
https://www.mywestnet.com/product/dlink-usb30-to-gigabit-ethern-dub-1312
