### ISSUE TITLE
Mail hyperlink for order status

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#341]
Kolatos

Το hyperlink που υπάρχει στο template του μέιλ επιβεβαίωσης παραγγελίας "Μπορείτε να δείτε την κατάσταση της παραγγελίας σας [εδώ](http://url5203.shopranos.eu/ls/click?upn=RH8ngsTfmLHMqqIzevmuGoXbaL9C5DCVSaeGnia0-2FH1Nan9iHkS9syEEQ2VYIEUS2rHh_YDSgmT0mPbRr0YqrPAXOJ2nb81DgEZ16kprfWYeMIdthbyKHxxhV0dwqAixmaHIbDMxOW4U8pIQNwQTSWkseg5v3DRk1a5o-2BbopxAJwdzszmHQ1MHlddC8HZEPKelvgUu79rCfd1SYNud9n3fxJsiYnmuTQWf3X38Il2rlzpYzDUtBO-2BOkMK1Ly306LDkumXKCTF-2F5Me-2FFG-2Fsz1pfliSTQk6Wn6VOHla7eAD4R5pg0JI-2FBbBDcTWL3SM3bAXApBMY9dLYscqaJvtSD1gyY84IEg-2FUvaAs5qZTu3XWzU9jO0-3D)."

μας οδηγεί στην αρχική.

Το ίδιο πρόβλημα υπάρχει και σε άλλες εγκαταστάσεις.

**Comment by AlexandrosStypsianos** [comment]
Το ίδιο και στον πελάτη **Παπαποστόλου** εάν δεν γίνει μαζικά!

**Comment by atsta** [comment]
@Vlefteris92 @AlexandrosStypsianos το διόρθωσα να πηγαίνει στη σελίδα παραγγελιών του πελάτη.
