### ISSUE TITLE
Different language in mail hint

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#343]
Στα hints που έχουν προστεθεί στα mails, το "Τ" στο {{Βutton_Τext}} είναι ελληνικό, με αποτέλεσμα αν το κάνουμε αντιγραφή και επικόλληση στο body να μην το αναγνωρίζει ως μεταβλητή.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/d93d742b-4a59-4835-bd9f-9cd4b804edfa)

(Αριστερά ο ASCII code για το "Τ" που έχει γίνει αντιγραφή από το hint, δεξιά εικόνα ο ASCII code για το αγγλικό "Τ")

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/c36da51a-d918-4764-914e-b3854ec7264f)

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε
