### ISSUE TITLE
Terms of use link discontinue

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#346]
Κατά την πρόσκληση χρήστη σε οποιαδήποτε εγκατάσταση το link για τους όρους χρήσης δεν οδηγεί πουθενά.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/cd613ee8-71cb-4ddf-ac2e-695c3e885b47)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/5bb0bbae-b1df-4508-8362-d4b6e685a318)

**Comment by spyroskaravanis** [comment]
@dikoutas Ποιο πρέπει να είναι το κείμενο? Μιλήστε με το legal.

**Comment by atsta** [comment]
@raniavch επικοινωνήστε με το legal να μας δόσουν όρους και προϋποθέσεις

**Comment by spyroskaravanis** [comment]
Να περαστεί από φανή
