### ISSUE TITLE
Catalog Price display twice

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#349]
ΚΡΗΝΗ

Εμφανίζεται η τιμή του πελάτη 2 φορές στον κατάλογο. Στη σελίδα προϊόντος φαίνεται κανονικά.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/3afd56f7-2a60-4473-a45c-d28a6f391f4e)

**Comment by Vlefteris92** [comment]
Επίσης 2 φορές εμφανίζονται και οι διαγραμμένες τιμές στο mini cart 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/1f204ff3-f4e8-4ad7-acd9-0ff50c07fcaf)

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε. Χρειάζεται update theme.
