### ISSUE TITLE
Languages Addition (Client: Access/Medical Trade International )

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#350]
Στον πελάτη Access ζητήθηκε η προσθήκη επιπλέον γλώσσας στη σελίδα.
Ισπανικά και Ρώσικα. 
@dikoutas

**Comment by dikoutas** [comment]
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/149376730/46e14322-31e3-4f2a-893e-611655734525)

**Comment by dikoutas** [comment]
Δεν βγαίνουν άμεσα, ίσως σε κάποιο σπριντ του Μαρτίου.
