### ISSUE TITLE
Minimum Stock Quantity - Cart

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#352]
Kolatos

Όταν υπάρχει ελάχιστο όριο αποθέματος μεγαλύτερο από το απόθεμα, θα πρέπει να μην επιτρέπει την εισαγωγή του προϊόντος στο καλάθι και την ολοκλήρωση της παραγγελίας.

Είχε φτιαχτεί ώστε να κρύβεται το "Προσθήκη στο καλάθι" από το product page αλλά μπορεί ο πελάτης να το βάλει κανονικά από τη γρήγορη αναζήτηση του καλαθιού. Θα πρέπει να το απαγορεύει κι από εκεί.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/f411d6c8-c244-4da7-b40a-2b44ee2c3f94)

**Comment by atsta** [comment]
@Vlefteris92 Λύθηκε
