### ISSUE TITLE
Invalid file during cart import 

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#354]
Κατά την εισαγωγή καλαθιού εμφανίζει Invalid file και κολλάει εκεί.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/d79294df-e9fb-439d-a412-19acc3fef1ad)

**Comment by spyroskaravanis** [comment]
isxuei akoma?
