### ISSUE TITLE
B2C Checkout

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#358]
Pharmacyware

Σε σελίδες λιανικής, στο checkout αν δε βάλω Περιφερειακή Ενότητα και Χώρα δε με προχωράει. Επίσης δε βγάζει και μήνυμα λάθους.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/29a599c4-7247-4d09-9d7a-698c3d72de70)

**Comment by dikoutas** [comment]
@atsta , @konstantinossf , @Vlefteris92 

Παρακαλώ χρησιμοποιείστε το επισυναπτόμενο excel ως template για το ticket:

[https://softonetechnologiessa-my.sharepoint.com/:x:/g/personal/dkoutas_softone_gr/EfVP1iNl5VlClBMOdFRJjhwBFYuR3WAj8vFv9OlMbsrutg?e=IJhLLa](url)

**Comment by atsta** [comment]
<html>
<body>
<div ccp_infra_version='3' ccp_infra_timestamp='1709543227179' ccp_infra_user_hash='3308745775' ccp_infra_copy_id='1339bb9d-0e1b-4f7a-ac40-d93054caa7bf' data-ccp-timestamp='1709543227179'><html><head><meta name=ProgId content=Excel.Sheet><meta name=Generator content="Microsoft Excel 15"><style>table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Aptos Narrow", sans-serif;
	mso-font-charset:0;
	text-align:general;
	vertical-align:bottom;
	border:none;
	white-space:nowrap;
	mso-rotate:0;}
.xl16
	{font-weight:700;}
</style></head><body link="#467886" vlink="#96607D">
Πεδία | Υποχρεωτικότητα | Σχόλια
-- | -- | --
Όνομα | Υποχρεωτικό |  
Επίθετο -> Επώνυμο | Υποχρεωτικό |  
Αριθμός Τηλεφώνου | Υποχρεωτικό |  
Διεύθυνση email | Υποχρεωτικό |  
Διεύθυνση 1 | Υποχρεωτικό |  
Διεύθυνση 2 | Προαιρετικό |  
Πόλη | Υποχρεωτικό |  
Περιφερειακή Ενότητα -> Νομός | Προαιρετικό | Μήπως κάνουμε drop down list
Χώρα | Υποχρεωτικό | Μήπως το γεμίζουμε από ip με κάποιο free service
Ταχυδρομικός Κώδικας | Υποχρεωτικό |  
  |   |  
Σε περίπτωση που η διεύθυνση αποστολής είναι διαφορετική τα ίδια πεδία είναι υποχρεωτικά και για τον παραλήπτη |   |  
Επίσης ας βάλουμε ένα κόκκινο αστεράκι στα υποχρεωτικά πεδία για να υποδηλώνεται η υποχρεωτικότητα |   |  
Και ας βγάζουμε κάποια ένδειξη που να ενημερώνει το χρήστη ότι πρέπει να συμπληρώσει τα υποχρεωτικά πεδία αν πατήσει "Επόμενο" χωρίς να τα έχει συμπληρώσει |   |  

</body></html></div>
</body>
</html>

**Comment by atsta** [comment]
Επιλογή Τιμολόγιο 



Πεδία | Υποχρεωτικότητα | Σχόλια
-- | -- | --
Στοιχεία τιμολογίου |   |  
Όνομα εταιρείας | Υποχρεωτικό |  
Επάγγελμα | Υποχρεωτικό |  
ΔΟΥ | Υποχρεωτικό |  
ΑΦΜ | Υποχρεωτικό |  
Διεύθυνση χρέωσης |   | Δεν είναι δόκιμη εδώ αυτή η ενότητα, παραμένουμε στα στοιχεία του τιμολογίου
Ονομα |   | Δεν υπάρχει φυσικό πρόσωπο εδώ
Επίθετο |   | Δεν υπάρχει φυσικό πρόσωπο εδώ
Διεύθυνση 1 | Υποχρεωτικό |  
Διεύθυνση 2 | Προαιρετικό |  
Πόλη | Υποχρεωτικό |  
Περιφερειακή Ενότητα -> Νομός | Υποχρεωτικό |  
Χώρα | Υποχρεωτικό |  
Εταιρικό Τηλέφωνο | Προαιρετικό |  
  |   |  
Στοιχεία Παραλήπτη |   |  
Όνομα | Υποχρεωτικό | Τα στοιχεία του φυσικού προσώπου
Επίθετο -> Επώνυμο | Υποχρεωτικό | Τα στοιχεία του φυσικού προσώπου
Αριθμός τηλεφώνου | Υποχρεωτικό | Τα στοιχεία του φυσικού προσώπου
email | Υποχρεωτικό | Τα στοιχεία του φυσικού προσώπου
  |   |  
Picture |   | Εδώ θέλουμε το default setting να είναι η περίπτωση διαφορετικής διεύθυνσης παραλήπτη από τη διεύθυνση έκδοσης του τιμολογίου. Σε περίπτωση που ο χρήστης επιλέξει κοινή διεύθυνση δε χρειάζεται τίποτα από τα παρακάτω
  |   |  
Διεύθυνση αποστολής |   |  
Διεύθυνση 1 | Υποχρεωτικό |  
Διεύθυνση 2 | Προαιρετικό |  
Πόλη | Υποχρεωτικό |  
Χώρα | Υποχρεωτικό |  
Νομός | Υποχρεωτικό |  
  |   |  
Επίσης ας βάλουμε ένα κόκκινο αστεράκι στα υποχρεωτικά πεδία για να υποδηλώνεται η υποχρεωτικότητα |   |  
Και ας βγάζουμε κάποια ένδειξη που να ενημερώνει το χρήστη ότι πρέπει να συμπληρώσει τα υποχρεωτικά πεδία αν πατήσει "Επόμενο" χωρίς να τα έχει συμπληρώσει |   |

**Comment by raniavch** [comment]
έφυγε το radio button που μπορώ να επιλέξω ίδια διεύθυνση χρέωσης ή διαφορετική. τώρα είναι default η διαφορετική διεύθυνση αποστολής.


![Image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/163513617/8d3f933e-765f-47e6-9753-2c0450d0c552)
