### ISSUE TITLE
B2C pdf Notes

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#359]
Pharmacyware

Aν δε βάλω notes στην παραγγελία το βγάζει (UNDEFINED) στο PDF 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/122784b0-ec6c-4ad8-ba24-1b0fdba90248)

**Comment by atsta** [comment]
@Vlefteris92 έχει λυθεί.
