### ISSUE TITLE
B2C Product Page Layout-Units Problem

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#362]
Σε έλεγχο στο demo b2c Pharmacyware  παρτηρήθηκε ότι στο product page  έρχεται λάθος το λεκτικό της μονάδας μέτρησης.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/d98ce594-a17f-41bb-ad0f-8637ec018448)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/fb145d8a-33ef-4eb0-9bd4-2b83fc0aee6f)

Έαν στην τιμή χονδρικής δηλώσουμε μονάδα μέτρησης, τότε αλλάζει και στο product page.

**Comment by spyroskaravanis** [comment]
Άλλη μονάδα στο listing σε σχέση με το single product
