### ISSUE TITLE
Anthesis order PDF customize

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#364]
Η ζήτηση του πελάτη είναι να αφαιρεθούν οι αξίες στο pdf  παραγγελιών που βγάζει το Shopranos.

![AnthesisPDF](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/e8818daa-a052-4fc5-a04e-478322d94a4d)
@dikoutas

**Comment by spyroskaravanis** [comment]
Με  setting ωα ορίζει πεδία.

**Comment by dikoutas** [comment]
[like]  Dimirtis Koutas reacted to your message:
________________________________

**Comment by atsta** [comment]
@AlexandrosStypsianos done
