### ISSUE TITLE
Δε φαίνονται οι ανακοινώσεις ως popup στο site

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#365]
EURONICS

@dikoutas 

Φαίνονται στις ανακοινώσεις του χρήστη αλλά όχι ως popup

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/e044d910-9f80-4950-8293-8bf6ace5a909)

**Comment by dikoutas** [comment]
[like]  Dimirtis Koutas reacted to your message:
________________________________

**Comment by konstantinossf** [comment]
Για εμφανιστεί το announcement σε popup πρέπει να ενεργοποιήσουμε το configuration από το admin (Layout Design -> Theme Configurator -> Header -> Add announcement). 
Το popup εμφανίζεται μία φόρα στο χρήστη (εντός των ημερομηνιών που έχει σεταριστει). 
Επίσης παραμένει διαθέσιμο εντός των ημερομηνιών και στο προφίλ του χρήστη.
