### ISSUE TITLE
Δε φαίνονται οι παραγγελίες στην καρτέλα του πελάτη στο Site

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#366]
EURONICS

@dikoutas 

Έχει γίνει παραγγελία με το συγκεκριμένο χρήστη στις 21/2 αλλά δε φαίνεται στο site στο ιστορικό

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/65558739-7596-4cfd-a18e-fe44f2fdd496)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/3ba61ab7-d6db-4f3c-be52-612b20e7cefa)

**Comment by dikoutas** [comment]
[like]  Dimirtis Koutas reacted to your message:
________________________________
From: Voulgaris Eleutherios ***@***.***>
Sent: Thursday, February 22, 2024 2:25:14 PM
To: Softone-Technologies-S-A/Shopranos-Issue-Tracker ***@***.***>
Cc: Dimirtis Koutas ***@***.***>; Assign ***@***.***>
Subject: [Softone-Technologies-S-A/Shopranos-Issue-Tracker] Δε φαίνονται οι παραγγελίες στην καρτέλα του πελάτη στο Site (Issue #366)

ΠΡΟΣΟΧΗ! CAUTION! External email. DO NOT open attachments or click on links unless this email comes from a known sender and you know the content is safe.

EURONICS

Έχει γίνει παραγγελία με το συγκεκριμένο χρήστη στις 21/2 αλλά δε φαίνεται στο site στο ιστορικό

image.png (view on web)<https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/65558739-7596-4cfd-a18e-fe44f2fdd496>

image.png (view on web)<https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/3ba61ab7-d6db-4f3c-be52-612b20e7cefa>

**Comment by spyroskaravanis** [comment]
Αυτό που βλέπουμε δεν είναι ιστορικό παραγγελιών αλλά καρτέλα πελάτη. Η καρτέλα δείχνει αξιακές κινήσεις δηλαδή τιμολόγια, πιστωτικά κλπ. Η παραγγελία συνήθως δεν κάνει αξιακή κίνηση.

**Comment by dikoutas** [comment]
@Vlefteris92
