### ISSUE TITLE
Λάθος ημερομηνία στις περασμένες παραγγελίες στο προφίλ

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#367]
EURONICS

@dikoutas 

Οι παραγγελίες που εμφανίζονται στον λογαριασμό πελατών (οι παλαιές) ενώ λένε μια ημερομηνία, αυτή δεν αντιστοιχεί στην πραγματικότητα

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/22d8c282-09bc-4d74-b0c3-0af441aacdb9)

**Comment by dikoutas** [comment]
[like]  Dimirtis Koutas reacted to your message:
________________________________
From: Voulgaris Eleutherios ***@***.***>
Sent: Thursday, February 22, 2024 2:45:47 PM
To: Softone-Technologies-S-A/Shopranos-Issue-Tracker ***@***.***>
Cc: Dimirtis Koutas ***@***.***>; Assign ***@***.***>
Subject: [Softone-Technologies-S-A/Shopranos-Issue-Tracker] Λάθος ημερομηνία στις περασμένες παραγγελίες στο προφίλ (Issue #367)

ΠΡΟΣΟΧΗ! CAUTION! External email. DO NOT open attachments or click on links unless this email comes from a known sender and you know the content is safe.

EURONICS

@dikoutas<https://github.com/dikoutas>

Οι παραγγελίες που εμφανίζονται στον λογαριασμό πελατών (οι παλαιές) ενώ λένε μια ημερομηνία, αυτή δεν αντιστοιχεί στην πραγματικότητα

image.png (view on web)<https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/22d8c282-09bc-4d74-b0c3-0af441aacdb9>

**Comment by spyroskaravanis** [comment]
Δεν καταλαβαίνω ακριβώς το θέμα θέλω επεξήγηση.

**Comment by Vlefteris92** [comment]
@spyroskaravanis φαίνεται πως ως ημερομηνία εισαγωγής των παραγγελιών παίρνει την ημερομηνία εισαγωγής της παραγγελίας στο shopranos, όχι την ημερομηνία καταχώρησης. Οπότε όλες τις προγενέστερες παραγγελίες τις βγάζει με την ημερομηνία που κάναμε full import στο shopranos.

**Comment by dikoutas** [comment]
Αντί για insert date θέλουμε order date ή softone date

**Comment by AlexandrosStypsianos** [comment]
Παρόμοιο πρόβλημα παρατηρήθηκε και στον πελάτη Roma hellas.

**Comment by atsta** [comment]
@Vlefteris92 @AlexandrosStypsianos έχει διορθωθεί. Στη euronics το εχω στρωσει εγω. Για όσους εχουν custom script χρειαζεται η αλλαγη που ειπαμε. Επίσης αμα γκρινιαξει κανεις αλλος κάνε του ένα manual sync για τα παλια δεδομενα. Τα καινουρια θα μπαινουν σωστα. Α και update theme για το προφιλ.
