### ISSUE TITLE
Δεν ανανεώνεται η κατάσταση της παραγγελίας σύμφωνα με το Softone

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#368]
EURONICS

@dikoutas 

Δεν ανανεώνεται η κατάσταση της παραγγελίας σύμφωνα με το "Κατάσταση e-shop" του Softone

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/6a5fc7d3-41f8-4c6f-90fe-aeab22d7a022)

**Comment by dikoutas** [comment]
[like]  Dimirtis Koutas reacted to your message:
________________________________
From: Voulgaris Eleutherios ***@***.***>
Sent: Thursday, February 22, 2024 2:50:11 PM
To: Softone-Technologies-S-A/Shopranos-Issue-Tracker ***@***.***>
Cc: Dimirtis Koutas ***@***.***>; Assign ***@***.***>
Subject: [Softone-Technologies-S-A/Shopranos-Issue-Tracker] Δεν ανανεώνεται η κατάσταση της παραγγελίας σύμφωνα με το Softone (Issue #368)

ΠΡΟΣΟΧΗ! CAUTION! External email. DO NOT open attachments or click on links unless this email comes from a known sender and you know the content is safe.

EURONICS

@dikoutas<https://github.com/dikoutas>

Δεν ανανεώνεται η κατάσταση της παραγγελίας σύμφωνα με το "Κατάσταση e-shop" του Softone

image.png (view on web)<https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/6a5fc7d3-41f8-4c6f-90fe-aeab22d7a022>
