### ISSUE TITLE
Related Products με βάση την κατηγορία

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#37]
Θα είναι χρήσιμο στα related, για να μην προστίθονται 4 προϊόντα τουλάχιστον σε κάθε προϊόν με το χέρι, να έχει επιλογή να εμφανίζει X αριθμό προϊόντων στην ίδια κατηγορία.

**Comment by spyroskaravanis** [comment]
this._findProductsByCategory (page, pagesize, categoryId, callback)
