### ISSUE TITLE
"Forgot my password" does nothing

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#370]
BOOS και σε όλους τους πελάτες

Όταν κάνουν κλικ στο σύνδεσμο για υπενθύμιση κωδικού δε γίνεται τίποτα. Έχουμε φτιάξουμε και email profil αλλά δε στέλνει κάτι.

**Comment by dikoutas** [comment]
Δείχνει blocker, να το δούμε @spyroskaravanis ?

**Comment by atsta** [comment]
@dikoutas @Vlefteris92 έχει λυθεί
