### ISSUE TITLE
Discount price same as wholesale price

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#372]
Cretan International

Εμφανίζεται διαγραμμένη τιμή ίδια με την αρχική στον κατάλογο.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/b9e990fe-5542-4ea5-acf8-b6fef2421979)

**Comment by dikoutas** [comment]
h-case λόγω δεκαδικών, μπορεί να περιμένει 1 sprint νομίζω.

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε.update theme
