### ISSUE TITLE
Error saving page

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#373]
Μαζιώτης
https://kavamazioti.shopranos.eu/fylladia

Έχουμε το παρακάτω σφάλμα κατά την αποθήκευση σελίδας.
Προσπαθώ να την ενεργοποιήσω και πατάω αποθήκευση και εμφανίζει το παρακάτω.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/06908a63-c2be-4f38-bba7-2496c0880973)

**Comment by atsta** [comment]
@Vlefteris92 εχει λυθει
