### ISSUE TITLE
Filter Price Problem.

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#374]
Κατα την εφαρμογή του φίλτρου τιμής οταν ο πελάτης έχει τιμολογιακή πολιτική  παρατηρήθηκε οτι το φίλτρο λάμβανει υπόψη τη αρχική τιμή και όχι την εκπτωτική.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/7d53eacc-6677-4e42-b07b-246283650d5e)
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/bb277c11-c95f-46e1-aed3-b6d66b68c61d)

**Comment by atsta** [comment]
@AlexandrosStypsianos δεν μπορούμε να εφαρμόσουμε φιλτράρισμα στις τιμές πελάτη by design. Δεσμευόμαστε τεχνικά επειδή δεν κρατάμε κάπου αποθηκευμένες τις τιμές. Το πρόβλημα αυτό θα λυθεί όταν ενσωματώσουμε τη λειτουργικότητα των τιμοκαταλόγων @spyroskaravanis
