### ISSUE TITLE
Search page cannot be published

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#375]
Βάβλης

Κατά τη προσπάθεια δημοσίευσης της σελίδας αναζήτησης σκάει και δε γίνεται ποτέ.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/66adb4e5-beed-4a89-bfa0-a6f1066036c5)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/c714395b-73f8-4ef9-8962-cd0bbe7d4077)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/83f0cb53-5374-470b-9314-e46387cfad01)

**Comment by atsta** [comment]
@Vlefteris92 Λύθηκε
