### ISSUE TITLE
Monthly Transactions bug on site

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#378]
Euronics

Στο Site δε φαίνεται η μηνιαία κίνηση, ενώ φαίνεται στην καρτέλα του πελάτη στο διαχειριστικό.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/8b5373b7-3322-45d7-acee-5a60afb0a606)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/f235c3c5-f0e3-4d49-b476-8910c9d1638e)

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε.

**Comment by dikoutas** [comment]
[like]  Dimitris Koutas reacted to your message:
________________________________
