### ISSUE TITLE
send mail for availability

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#379]
Σχετάκης
@dikoutas 

Ζήτησε να μπορεί να λαμβάνει mail ο χρήστης όταν γίνεται ξανά διαθέσιμο ένα προϊόν (ακόμα και με custom).
Αυτό στο e-shop.gr γίνεται βάζοντας το προϊόν σε wishlist (favourite list like) και ειδοποιείσαι στο mail σου κάθε φορά που η κατάσταση διαθεσιμότητάς του γίνεται από "out of stock" σε "available"

**Comment by raniavch** [comment]
#6585

**Comment by raniavch** [comment]
https://github.com/Softone-Technologies-S-A/Ecom/issues/6585

**Comment by spyroskaravanis** [comment]
Να περαστεί από φανή
