### ISSUE TITLE
Wrong catalog discount price

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#380]
BOOS

Στον κατάλογο εμφανίζει τιμή έκπτωσης μεγαλύτερη από τη χονδρική η οποία δεν αντιστοιχεί σε καμία δηλωμένη τιμή.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/852f6153-e657-45b9-963d-6f02c5de311d)

**Comment by atsta** [comment]
@Vlefteris92 Λύθηκε
