### ISSUE TITLE
Μηνιαία κίνηση, προφίλ πελάτη

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#382]
Euronics 

Δεν υπάρχουν δεδομένα στη μηνιαία κίνηση στο προφίλ του πελάτη στο site, ενώ στο διαχειριστικό εμφανίζονται κανονικά. 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/3331d2eb-232c-44fe-b48f-520847839b22)
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/27534e5f-1e77-47e5-a119-f669c20f41ee)

**Comment by dikoutas** [comment]
Sprint 2080

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε. Στη Mega το ανέβασα. Όποιοι άλλοι έχουν το θέμα θέλει update theme.
