### ISSUE TITLE
Brands import from MTRMARK

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#383]
Roma Hellas

Δε γίνεται συγχρονισμός κατασκευαστών από το MTRMARK .
Πατάμε το συγχρονισμό και δεν κάνει κάτι.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/58f27b47-45da-485f-b25b-b6e107b5b092)
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/2957f8fc-f6c3-42f3-9b6d-ba2a11af12ed)

**Comment by dikoutas** [comment]
΄Εχουμε κάποιο update για αυτό; Μου δείχνει urgent @atsta

**Comment by dikoutas** [comment]
Το πρόβλημα παρουσιάζεται σε όλους

**Comment by spyroskaravanis** [comment]
οι κατασκευαστές έχουν μπει κανονικά
