### ISSUE TITLE
Fast Entry Mode Problem

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#384]
Κατά την αλλαγή της εμφάνισης της λίστας σε γρήγορη εισαγωγή παρατηρήθηκε 

- Απο τη δέυτερη σελίδα μιας λίστας και μετά εμφανίζονται τα είδη με  default  ποσοτητα  (1 )με αποτέλεσμα όταν επιλέγω προσθηκη με (+) να προσθέτει 2 στο καλαθι.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/94d9e7ff-8478-43bb-8470-0852f8fc7dac)

- Παρατηρήθηκε επίσης οτι το πληκτρο (+) μπορει να μην λειτουργεί πάντα και να χρειάζεται ο χρήστης να μπεί πρώτα σε ένα είδος να επιλέξει (προσθήκη στο καλάθι). Σε δοκιμή που εγίνε με αυτον το τρόπο διορθώνεται το συγκεριμενο πρόβλημα.
- Επίσης ανάλογα το μέγεθος της περιγραφής (σε αριθμό χαρατήρων) επηρεάζει την στοίχηση με αποτέλεσμα να επηρεάζει και εμφανισιακά τη σελίδα.

Οι  πέλάτες που παρατηρήθηκε είναι η ACCESS και ο Παπαποστόλου.

**Comment by atsta** [comment]
@AlexandrosStypsianos επελεξε "Default" Προβολή Και επιλογη εμφανισης "λιστα"
