### ISSUE TITLE
New Languages Layout Problem

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#385]
Κατα την εφαρμογή των νέων γλωσσών Ισπανικά,Ρωσικά,Πολωνικά  στην drop down  λίστα του b2b εμφανίζονται ως Unknown.

Επίσης δεν γίνεται ούτε μετάφραση κάποιου στοιχείου του B2B. 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/65206e10-e521-4617-8b45-812d314e8a60)

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε.
