### ISSUE TITLE
Product Variants  Layout Translate 

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#386]
Χρειάζεται διόρθωση το λεκτικό των διαστάσεων στο  product page  στους πελάτες 'ΤΣΙΟΛΑΚΗΣ' και 'ΤΕΛΙΔΗΣ'.
Μπορεί να μεταφραστεί στους παραπάνω πελάτες το λεκτικό σε "Διαστάσεις".

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/30b51a87-3108-4d91-84ea-299ba906af97)

**Comment by dikoutas** [comment]
Δε μπορεί να το κάνει το support επειδή δεν είναι ανοικτό το customization @atsta
