### ISSUE TITLE
B2B: Change checkout page message for not logged in

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#388]
Anelysis

Ζητούν να αλλαχθεί το μήνυμα της σελίδας checkout όταν δεν είναι logged in (You are not authorized to perform this action) σε κάποιο μήνυμα που θα παραπέμπει το χρήστη να κάνει login. Καλό θα ήταν να μπει γενικά αυτό στο Shopranos.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/eefd0ab7-99f5-4c91-923d-fdfbcf52d4a5)

**Comment by spyroskaravanis** [comment]
redirect στο login και πάλι πίσω

**Comment by spyroskaravanis** [comment]
Να περαστεί από φανή
