### ISSUE TITLE
To login από την είσοδο δεν έχει σωστό authorization, δεν με αφήνει να μπω

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#39]
**Στο /login με τα ίδια στοιχεία μπορώ να εισέλθω

![image](https://user-images.githubusercontent.com/113907624/197744651-29832863-d56d-4ca7-8358-90efa6d2e93d.png)

**Comment by clioli0s** [comment]
Σε staging δουλέυει κανονικά, οπότε χρειάζεται ένα publish to θέμα.
