### ISSUE TITLE
Cannot upload image when there is "&" in folder's title

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#390]
Anelysis

Όταν προσπαθώ να ανεβάσω φωτογραφίες σε φάκελο που περιέχει το "&" στον τίτλο, κόβει τη διαδρομή μέχρι πριν το χαρακτήρα και δεν ανεβάζει την εικόνα ποτέ.

![Screenshot 2024-03-28 125905](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/f47c35c8-ce74-492d-a688-46f90afb4053)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/13a37d93-09b9-43c6-aadb-edab82c1f861)

**Comment by spyroskaravanis** [comment]
Να περαστεί από φανή
