### ISSUE TITLE
Anelysis Sync Problem on specific items

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#391]
Στον πελάτη Anelysis  σε αλλαγές που έγιναν στα ονόματα  είδών στο Soft1  δεν ενημερώνεται το Shopranos.
Το πρόβλημα εντοπίζεται στο πεδίο mtrl_CCCWEBNAME που είναι ο τίτλος.
Δεν παρατηρήθηκε κάποιο σφάλμα κατα τον συγχρονισμό.

Παράδειγμα με Κωδικός είδους: BIJUR 300157

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/b2401e37-92f8-4487-a526-8199d56283b6)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/f91df59f-1102-46bd-8b61-f5f97c94eb77)

@dikoutas

**Comment by dikoutas** [comment]
@spyroskaravanis δες το λίγο σε παρακαλώ.

**Comment by spyroskaravanis** [comment]
Δεν είναι πρόβλημα έχει βάλει την περιγραφή σε λάθος εταιρεία στο Soft1
