### ISSUE TITLE
Bennett χρεώσιμο 2 ωρών - προσθήκη σημείωσης

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#392]
Bennett 

**_χρεώσιμο 2 ωρών έως 5/4_**

Θέλουν να προστεθεί το μήνυμα «Στον υπολογισμό της τελικής αξίας δεν περιλαμβάνεται ο Π.Φ.Σ και η έκπτωση που αναλογεί.»
στα παρακάτω σημεία:

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/c62d5fa5-f0fe-40ad-9988-e1b60f8b8e7a)

<img width="573" alt="pdf bennett" src="https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/6ede6feb-1210-40fc-9477-131515ea946b">

**Comment by atsta** [comment]
@Vlefteris92 είναι ετοιμο. Χρειάζεται κάποιος να περάσει τις μεταφράσεις του επαναχρησιμοποιούμενου component _orders_ στο _custom_order_profile_ ώστε να στρωθούν οι μεταφράσεις. 

Αφήνω customization ανοιχτό μέχρι να γίνει και πείτε μου να το κλείσω

**Comment by atsta** [comment]
@Vlefteris92 ειμαστε οκ εδω;

**Comment by Vlefteris92** [comment]
έχει υλοποιηθεί.
