### ISSUE TITLE
Cookies expiration date

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#393]
Παρατηρήθηκε πρόβλημα κατά την εφαρμογή των  cookies  όσον αφορά την ημ/νια λήξης η οποία δεν λαμβάνεται υπόψην με αποτέλεσμα σε κάθε αλλαγή σελίδας,refresh να χρειάζεται αποδοχή απο τον χρήστη.

Έγινε δοκιμη στους παράκατω πελάτες:
Roma hellas
Αγροτικο σπίτι
Ζαρμπάνης

**Comment by atsta** [comment]
@AlexandrosStypsianos έχει λυθεί. update theme

**Comment by AlexandrosStypsianos** [comment]
Έγινε update και δοκιμή αλλά εξακολουθεί το πρόβλημα.
Επίσης στον πελάτη ROMA HELLAS παρατηρήθηκε 'οτι  δεν εμφανίζεται καθόλου η επιλογή αποδοχής στην αρχική σελίδα.
