### ISSUE TITLE
Add To Cart-Auto filling Max Qty

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#394]
Πελάτης Roma Hellas

Ζητήθηκε κατα την σύμπληρωση ποσότητας στο είδος για προσθήκη στο καλάθι, εαν η ποσότητα ξεπερνάει την ποσότητα αποθέματος  να συμπληρώνεται αυτόματα αυτη του συνολικού αποθέματος του είδους.

@dikoutas

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε cross
