### ISSUE TITLE
Order QR Code  Problem

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#395]
Κατα το σκανάρισμα του Qr Code στο pdf παραγγελίας το  url  που παράγεται οδηγεί σε κενή σελίδα.

Παράδειγμα απο τον πελάτη  krannich. 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/5b8ef3cb-05bf-41bf-8c59-2bbd8c0d44ff)

https://krannichsolar.shopranos.eu/invoice/6e66b0ad-7252-4757-831e-b6b84b3aaed4/ORD000000003

**Comment by atsta** [comment]
@AntChouv βαλτο να πηγαινει στις παραγγελιες του στο προφιλ

**Comment by dikoutas** [comment]
@AntChouv σε ποιά κατάσταση είναι αυτό; αν είναι done να κάνουμε update το status, είναι η τελευταία τους εκρεμότητα για να βγούν live.

**Comment by dikoutas** [comment]
@atsta μήπως ξέρεις που βρισκόμαστε σε αυτό; Είναι reasonable request.

**Comment by dikoutas** [comment]
@atsta επικοινώνησε και πάλι ο πελάτης και το θέλει.

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε. το εβαλα να κανει redirect στις παραγγελίες του χρηστη https://krannichsolar.shopranos.eu/profile/orders
