### ISSUE TITLE
4th level Category Disappear (Phone device)

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#396]
Πελάτης Anelysis.

Κατά την περιήγηση στις κατηγορίες του ΜΕΝΟΥ απο κινητό τηλέφωνο η tablet  όταν επιλέγω να ανοιξω το 4ο επίπεδο απο μια κατηγορία δεν ανοίγει και με επιστρέφει στο προηγούμενο επιπεδο.

![Screenshot 2024-04-08 153800](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/42499d9e-9533-4992-851b-8c2f03700a86)

**Comment by dikoutas** [comment]
Είχε παρουσιαστεί το καλοκαίρι του '23, λύθηκε και ξαναπαρουσιάστηκε. Το είχε φτιάξει ο Λιόλιος.

**Comment by dikoutas** [comment]
@nikosgio μπορείς να ρωτήσεις τον @clioli0s για αυτό, είναι μικρό effort.

**Comment by atsta** [comment]
@AlexandrosStypsianos έχει λυθεί.
