### ISSUE TITLE
Λάθος παραστατικό μετά από επιλογή στην καρτέλα πελάτη.

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#399]
Euronics

Όταν πατάμε για εμφάνιση κάποιου παραστατικού στην καρτέλα πελάτη, εμφανίζεται κάποιο άλλο.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/469b3b7c-5ccc-443d-b4c0-2b9e608d60a9)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/85a77e6a-d029-426a-aec8-c7e8907b2f04)

**Comment by atsta** [comment]
@Vlefteris92 ειναι θεμα s1
