### ISSUE TITLE
Image Replace

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#401]
Anelysis

Κατά το ανέβασμα νέων εικόνων, ζητούν η αντικατάσταση να γίνεται σε οποιοδήποτε σημείο του media gallery ώστε να μην ψάχνουν σε ποιο φάκελο είναι η παλαιότερη φωτογραφία.

**Comment by atsta** [comment]
@Vlefteris92 πολύ δύσκολη υλοποίηση, δεν ξέρω εάν αξίζει τον κόπο. Δώσε μας feedback @dikoutas
