### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#402]
Anelysis

Στον αυτόματο συγχρονισμό παραλείπει κάποια προϊόντα, τυχαία κάθε φορά. Αναφέρουν πως αν αλλαχθεί το soeshop ενός προϊόντος σε άλλη τιμή και μετά ξανά σε 3, στον επόμενο συγχρονισμό το είδος ανεβαίνει. (Ίσως επειδή έχουν αρκετά προϊόντα και προτεραιοποιείται με αυτό τον τρόπο;)
Το είχαμε δει και με το Σπύρο κάποια στιγμή και είχαμε παρατηρήσει πως ήταν τυχαία.

**Comment by dikoutas** [comment]
@spyroskaravanis Πολύ παρόμοιο με το #391 στο οποίο σε προσέθεσα ήδη.

**Comment by spyroskaravanis** [comment]
Δεν σχετίζεται το soeshop αλλα το upddate του soft1. Δηλαδή όταν αλλάζετε το soeshop ενημερώνετε το upddate. Πως ενημερώνουν τα είδη? Μήπως το upddate δεν αλλάζει?
