### ISSUE TITLE
Filters and Sort Options on Search Page

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#403]
Anelysis

Θέλουν να υπάρχουν επιλογές ταξινόμισης και φίλτρα στη σελίδα αναζήτησης.

**Comment by dikoutas** [comment]
@spyroskaravanis ας το δούμε αυτό πάνω στο καινούργιο layout design πλέον.

**Comment by spyroskaravanis** [comment]
Υπάρχει view με φίλτρα το ενεργοποίησα
