### ISSUE TITLE
Google Search and Google Merchant 

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#404]
Anelysis

Αναφέρουν πως υπάρχει πρόβλημα με τα παρακάτω εργαλεία.

- Google Search (μετά από 1 έτος δεν έχει διαβαστεί ακόμη σωστά το website) 
- Google Merchant (δεν υπάρχει sitemap generator)

Είχαν ζητήσει να μπει αρχείο html στο root.

 Επίσης εμφανίζεται το anelysis.shopranos.eu και δε θα έπρεπε γιατί έχουν δικό τους domain https://anelysis.com/

**Comment by dikoutas** [comment]
@atsta ας σβήσουμε απλά το anelysis.shopranos.eu

**Comment by dikoutas** [comment]
@atsta έχουμε κάποιο update για το πρώτο αίτημα....το sitemap ok γενικά πρέπει να το κάνουμε grooming.
