### ISSUE TITLE
BOOS Checkout Default Branch

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#409]
BOOS
Χρεώσιμο 3 ωρών

Σε κάθε πελάτη τους έχουν φτιάξει ένα υποκατάστημα που ονομάζουν κεντρικό (είναι πάντα το πρώτο υποκατάστημα). Θέλουμε κατά το ckeckout να μη λαμβάνεται υπόψιν ο ίδιος ο πελάτης ως οντότητα, αλλά να επιλέγεται by default το πρώτο υποκατάστημα που έχει ο πελάτης.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/74d1ef2c-d9c0-48d7-b33e-1fd1569469d4)

**Comment by Vlefteris92** [comment]
@atsta είναι έτοιμα
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/63243aa4-200b-4bab-8ae4-2791f226923e)

**Comment by atsta** [comment]
@Vlefteris92 τους ανεβασα θεμα και εκλεισα το customization. είναι done.
