### ISSUE TITLE
Email profile Invitation Problem

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#411]
Πελάτης ΖΑΡΜΠΑΝΗΣ

Κατά τη  δημιουργία καινούργιου  email προφίλ προσκλήσεων οταν δοκιμάζω να προσκαλέσω πελάτη το  email  που αποστέλεται είνια το  default.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/9678acc2-8488-46b2-bb04-50be921f8223)
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/8784bef4-a514-4567-b199-015009bf6008)

**Comment by Vlefteris92** [comment]
Το ίδιο και στον πελάτη BOOS

**Comment by atsta** [comment]
@AlexandrosStypsianos του ενημέρωσα το template. Το δοκιμάζεις αν είναι οκ;

**Comment by AlexandrosStypsianos** [comment]
@atsta Εγινε δοκιμή.Λειτουργεί κανομικα!

**Comment by atsta** [comment]
@AlexandrosStypsianos ενημερωσα και τη BOOS. οποτε μπορείς τσέκαρε το να το κλείσουμε
