### ISSUE TITLE
Orders on user profile

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#416]
Euronics

Πατώντας για εμφάνιση σε νέες παραγγελίες δεν εμφανίζει το popup

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/c75398a9-c432-4197-b166-7e3b0a681dc4)

**Comment by Vlefteris92** [comment]
Είναι οκ!

**Comment by dikoutas** [comment]
[heart]         Dimitris Koutas reacted to your message:
________________________________
