### ISSUE TITLE
Inventory -add to cart Problem 

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#419]
Πέλάτης ΡΟΜΑ HELLAS

Παρατηρήθηκε οτι σε ερκετά  είδη  δεν εμφανίζεται η προσθήκη στο καλάθι και επίσης δεν λειτουργούν τα μοντέλα διαθεσιμότητας.
Τα είδη έχουν κανονικά απόθεμα  και όταν  γίνει χειροκιντητη αλλαγή του αποθέματος τότε λειτουργούν κανονικά.

sku's  για δοκιμές: 1198007 , ZB-59398

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/c51faa38-030c-4025-8485-d7040c460ab3)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/9428c389-7be9-4dcc-88f9-a6e03a0ec0a2)

**Comment by AlexandrosStypsianos** [comment]
Παρατηρήθηκε επίσης  οτι εμφανίζονται λάθος αποτελέσματα και στο φίλτρο Διαθεσιμότητα. 
Το απόθεμα των ειδών έρχεται σωστά απο το Soft1.

**Comment by dikoutas** [comment]
@atsta ας το δούμε αυτό κατά προτεραιότητα.

**Comment by spyroskaravanis** [comment]
done
