### ISSUE TITLE
Δεν μου εμφανίζει τις λίστες για να προσθέσω προϊόν

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#42]
Έχει δημιουργηθεί τουλάχιστον 1 λίστα αλλά δεν εμφανίζεται για να προστεθεί το προϊόν σε αυτήν.
Το ίδιο και στο category page.

![image](https://user-images.githubusercontent.com/113907624/199441219-88b3ad1b-d058-4535-882e-b9e16ac6c0fb.png)

**Comment by spyroskaravanis** [comment]
Δες το default
