### ISSUE TITLE
Filter Availability Translate

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#420]
Στον πελάτη ΡΟΜΑ ΕΛΛΑΣ 
ζητήθηκε για λόγους εμφάνισης των λιστών να μεταφραστεί το φίλτο Availability.
 
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/5386411a-3fc5-45ef-8ca3-07a912f6a89c)

**Comment by dikoutas** [comment]
@tpolitis

**Comment by dikoutas** [comment]
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/149376730/36d7ff80-defb-4818-aa21-1ff7d1f28032)

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε.
