### ISSUE TITLE
 Layout Problem on Lists. Mobile Device.

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#421]
Στο πελάτη Access  
ο οποιος παίζει με mode εμφάνισης προιοντων  σε λίστα παρατηρήθηκε οτι όταν ανοίγει τη λίστα απο κινήτο τηλέφωνο κόβονται κάποια sku  και  οι μεγάλες περιγραφές ειδών  στην απο κάτω γραμμή με αποτέλεσμα να κοβόνται ολόκληρες λέξεις.
Επίσης όταν φορτώνεται η σελίδα για να εμφανιστεί η προσθήκη στο καλάθι  θα πρέπει ο χρήστης να κάνει  zoom out. 

![1714047591081](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/e359dfdb-8327-4202-9b6e-ea417bf4d2df)

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε, θελει update theme

**Comment by AlexandrosStypsianos** [comment]
Έχει ελεγχθεί. Είναι οκ.

**Comment by dikoutas** [comment]
[like]  Dimitris Koutas reacted to your message:
________________________________
