### ISSUE TITLE
New page draft

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#423]
ΤΕΛΙΔΗΣ
Το ίδιο έχει παρατηρηθεί και σε άλλες εγκαταστάσεις.

Κατά τη δημιουργία νέας σελίδας την ανοίγει αυτόματα σε draft και δεν αλλάζει το mode σε active ακόμα και με μεταβολή μετά.

**Comment by Vlefteris92** [comment]
Δεν έχει λυθεί το συγκεκριμένο.

**Comment by dikoutas** [comment]
Δεν έχει επιλυθεί @Vlefteris92

**Comment by atsta** [comment]
@Vlefteris92 το δοκιμασα και λειτουργει κανονικα. μπορεις να μου δωσεις τα reproduction steps;

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε, επιβεβαιωμένα
