### ISSUE TITLE
Filterlist 'Availability' title translation

### ISSUE THREAD

**Issue by tpolitis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#424]
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/136069353/11139711-13bb-4d8c-b860-c81eaade7b8c)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/136069353/9b24e0c0-ca70-45e7-b2c8-8f7fead46e70)

The translation must be added to shopranos.

**Comment by dikoutas** [comment]
Cancel καθότι ίδιο με το #420 που είναι στο τρέχον sprint.
