### ISSUE TITLE
ProductsImport CustomFields overwrite

### ISSUE THREAD

**Issue by tpolitis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#426]
Παρόλο που έχει αφαιρεθεί από τον **connector** στο **productsImport** ο κώδικας που κάνει resolve τα **custom fields**, κατά το import γίνεται overwrite σε αυτά.

**Comment by dikoutas** [comment]
@atsta βγαίνει ο πελάτης την άλλη εβδομάδα, ας το δούμε κατά προτεραιότητα, ειναι και γενικά θέμα που στο μέλλον λογικά θα προκύπτει πιο συχνά. Αν αλλάζω με το χέρι πεδια που κάνω και import το παίρνω πια πάνω μου manually εκεί που έχω κάνει αλλαγές. Πρέπει όμως να σκεφτούμε και έναν τρόπο να γυρνάω πίσω σε mode erp import και πάλι.
