### ISSUE TITLE
Header dissapear

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#427]
Γενική Εξοπλισμών

Δεν εμφανίζεται το header. Έχω δοκιμάσει να κάνω αποθήκευση σε όλες τις καρτέλες, αφαίρεση και προσθήκη του component, αλλαγή layout χωρίς αποτέλεσμα.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/e7e455ae-a18d-47fb-a13c-d773b62de924)

**Comment by atsta** [comment]
@Vlefteris92 Λύθηκε.
