### ISSUE TITLE
Dimensions bug

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#428]
ΤΕΛΙΔΗΣ

Δεν συγχρονίζει τις διαστάσεις (χρώμα/μέγεθος) ενώ είναι σεταρισμένα σωστά στο soft1.
πχ sku 4-26602
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/058f580d-22cb-48ed-ba81-f6ff8c86b861)
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/b9436f8c-729c-49b3-9dcd-bea9fd8fa7ce)

**Comment by dikoutas** [comment]
@atsta δεν είναι live αλλά το προχωράει και του είναι σημαντικό, το βάζω στο επόμενο sprint.
