### ISSUE TITLE
Single Blog - summaryHtml (undefinied)

### ISSUE THREAD

**Issue by tpolitis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#429]
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/136069353/95bdb336-3d75-4b2b-b42d-c09360130e89)

Το πεδίο summaryHtml στο singleBlog δεν έρχεται συμπληρωμένο.

**Comment by dikoutas** [comment]
@tpolitis ποιός είναι ο πελάτης; είναι σε όλους; πόσο σημαντικό είναι;

**Comment by tpolitis** [comment]
@dikoutas ο πελάτης είναι η Prime που θέλει να βγει άμεσα live. Τους το έχουμε πει για σήμερα.

**Comment by atsta** [comment]
@tpolitis λύθηκε.
