### ISSUE TITLE
Product page-Attributes view

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#430]
Πελατης ΠΙΤΟΣ,

Κατα την εμφάνιση των χαρακτηριστικών απο στη σελίδα του είδους εμφανίζονται κάποια σαν βασικά χαρακτηετιστικά και κάποια σαν επιπλέον χαρακτηριστικά.
Εχει δημιουργηθεί 1 πρότυπο χαρακτηριστικών με τις τιμές. 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/c921de46-6227-49cb-9e36-9017613f1423)

**Comment by dikoutas** [comment]
@atsta στο erp μάλλον είναι οκ, μπορούμε να σούμε λίγο το script? δεν είναι live, medium to low priority.

**Comment by spyroskaravanis** [comment]
Τι θέλει ο πελάτης?
