### ISSUE TITLE
Product save failure

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#432]
NOVART

Πολλά είδη δεν αποθηκεύονται όταν πατάμε save και εμφανίζει 500 internal server error.
Παράδειγμα τα παρακάτω.

![Screenshot 2024-05-10 165648](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/aaf17514-55ee-46d1-a2f3-32d04c449d09)
![Screenshot 2024-05-10 162741](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/17febf41-47a6-4f1d-ad45-86e858bd6cfb)

**Comment by atsta** [comment]
@Vlefteris92 έχει λυθεί
