### ISSUE TITLE
Filter Availability Problem

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#433]
Στο πελάτη ΡΟΜΑ HELLAS 

παρατηρήθηκε οτι στα φίλτρα διεθσιμότητας δεν υπολογίζονται τα είδη που εχουν απόθεμα 0.
Οσα είδη έχουν  θετικό απόθεμα υπολογίζονται ως διαθέσιμα.
Οσα έχουν αρνητικό υπολογίζονται ως μη διαθέσιμα.
Οσα έχουν 0  δεν υπολογίζονται ενω θα έπρεπε να φαίνοτναι στα <Μη διαθέσιμα>
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/89a6910a-4a32-48f4-94b3-82ad7687a4de)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/d08a8fb5-b56b-42c0-973c-2cf38891e4bf)

**Comment by dikoutas** [comment]
@atsta δείχνει πολύ εύκολο, ίσως απλά έχει μπει inventory < 0 αντί για inventory =< 0
