### ISSUE TITLE
Client Sync Problem 

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#434]
Στο πελάτη ΒΑΡΔΑΚΤΣΟΓΛΟΥ  δεν μπορούμε να συγχρονίσουμε πέλατες ενώ τα υπόλοιπα δεδομένα έρχονται κανοικά.
Ο πέλατης λόγω του ότι έχει Server 2008  εχει γυρίσει σε V1Script.

**Comment by dikoutas** [comment]
@atsta είναι demo... ο συγκεκριμένος δείχνει να ασχολείται, στη διακριτική σας ευχέρια τι θέλετε να κάνετε ανάλογα με το capacity.
