### ISSUE TITLE
Invoice Report Problem on Customer Profile

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#435]

**Comment by AlexandrosStypsianos** [comment]
Στον πελάτη ΣΚΟΡΔΑΚΗ 
παρατηρήθηκε ότι δεν εμφανίζονται τα παραστατικά στη καρτέλα πελάτη.
Τα υπόλοιπα εμφανίζονται κανονικά αλλα όταν αλλάζω έυρος ημ/νιων χάνονται. 

Δοκιμαστικός πελάτης: ΡΕΠΠΑΣ ΑΘ. ΑΡΓΥΡΙΟΣ - ΓΕΩΡΓΙΟΣ

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/5fc80d1a-c04f-4d98-a92f-417ea9e3af06)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/2681d951-f52c-4964-9950-a8b54d66d02d)

**Comment by dikoutas** [comment]
@atsta @AlexandrosStypsianos @raniavch φοβάμαι ότι θέλει κάποια διερεύνιση, γιατί δεν έχει εντοπιστεί το πρόβλημα.

**Comment by spyroskaravanis** [comment]
Να περαστεί από φανή
