### ISSUE TITLE
Connector-Fields Delete

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#436]
Κατα την παραμετροποίηση του Connector στα πεδία MPN  και GTIN  δινεται η δυνατότητα διαγραφής του πεδίου ώστε να μην ξανα συγχρονίσει.
Οποτε σε περιπτωση λάθους μπορούμε να το διορθώσουμε με διαγραφή κάποιων ειδών και εκ νέου συγχρονισμό.
Το ίδιο θα μπορούσε να γίνεται και στο πεδίο Περιγραφή διότι σε περίπτωση λάθους περιγραφών δεν μπορω να ξανα συγχρονίσω με κενό το πεδίο αυτο.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/b4976876-9efc-42e4-bcdf-3bc7032c2bba)

**Comment by dikoutas** [comment]
@atsta δεν επίγει επειδή υπάρχει workaround.

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε
