### ISSUE TITLE
EURO €  Symbol Order Pdf

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#437]
Στον πελάτη Krannich ζητήθηκε να εμφανίζεται στο pdf παραγγελίας το συμβολο του € σε όλες τις αξίες.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/d36e3db3-1168-48bc-bd74-0cea37ce4019)

**Comment by dikoutas** [comment]
@atsta μια βλακίτσα είναι αλλά ας το κάνουμε μήπως βγει και ησυχάσουμε.

**Comment by dikoutas** [comment]
Επικοινώνησε εκ νέου ο πελάτης και το θέλει @atsta

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε.
