### ISSUE TITLE
Product Sets Inventory

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#438]
ΔΑΣΚΑΛΟΠΟΥΛΟΣ

Σε συγχρονισμό σετ ειδών από το SOFT1 θα πρέπει να υπολογίζεται ως απόθεμα του σετ, το απόθεμα του είδους που έχει το μικρότερο. Αν πχ ο κωδικός 12345 (απόθεμα 5) και 12346 (απόθεμα 8) κάνουν το σετ 54321 θα πρέπει το απόθεμα του σετ να είναι 5.

**Comment by atsta** [comment]
@Vlefteris92 έχει λυθεί
