### ISSUE TITLE
Spanish Language Translate Problem.

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#439]
Στον πελάτη ACCESS, 
όταν κάνουμε μετάφραση στα Ισπανικά και αποθήκευση  δεν φαίνεται η αλλαγή στη σελίδα.
Παρατηρήθηκε και στο  header menu, footer αλλα και στο product page.

**Comment by AlexandrosStypsianos** [comment]
Παρατηρήθηκε οτι δεν κρατάει ούτε τις αλλαγές μετά από αποθήκευση στο διαχειρηστικό.

**Comment by dikoutas** [comment]
@atsta καλά είναι ;ow priority αλλά ας το δούμε στο επόμενο sprint μήπως είναι γενικότερο θέμα.

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε. Για να δουν ισπανικες μεταφρασεις στα menu items πρεπει να τις ορισουν και στο διαχειριστικο
