### ISSUE TITLE
Popup during checkout

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#441]
EURONICS
Ζητούν αν υπάρχει η δυνατότητα να εμφανίζεται Pop up ειδοποίησης κατά το κλικ του χρήστη στο «Ανάπτυξη καλαθιού» και «Ολοκλήρωση αγοράς» με προϊόντα που επισκέφτηκε πρόσφατα. Υπάρχει ήδη στο καλάθι αλλά το θέλουν και σε popup.

**Comment by atsta** [comment]
@Vlefteris92 θελουν να εμφανιζεται εναν Popup οταν πατουν "Αναπτυξη καλαθιου";

**Comment by dikoutas** [comment]
@atsta αυτό κατάλαβα, αλλά λέει επισκέφθηκε όχι αγόρασε. ΟΚ κάποια στιγμή πρέπει να το κάνουμε προιοντικά.
