### ISSUE TITLE
Filters back to top

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#442]
NOVART

Θέλει να μην πηγαίνει στην αρχή της σελίδας όταν επιλέγονται φίλτρα μέσα σε μια κατηγορία.

**Comment by atsta** [comment]
@dikoutas εχουν βασικο πακετο. εχει νοημα να μπει προιοντικα; θα τους επηρεασει ολους

**Comment by dikoutas** [comment]
> @dikoutas εχουν βασικο πακετο. εχει νοημα να μπει προιοντικα; θα τους επηρεασει ολους

@atsta δε νομίζω Αθηνά ότι είναι της παρούσης, είναι πολύ nice to have.

**Comment by dikoutas** [comment]
@atsta αλλάξανε τα πλάνα,  δυστυχώς το θεωρούν αυτοί high priority για να βγούνε....

**Comment by dikoutas** [comment]
> @dikoutas να δούμε πως μπορεί να ενσωματωθεί προϊοντικά, έχει νόημα να είναι cross-functionality;

Ναί θα ήταν καλό να μπεί προιοντικά καθαρτά για θέματα code integrity.

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε.
