### ISSUE TITLE
Products Empty list

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#443]
NOVART

Μερικές φορές, σε τυχαίες περιπτώσεις, δεν εμφανίζονται καθόλου τα προϊόντα μέσα στο διαχειριστικό.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/d90654fd-e28c-4e51-940e-6261cb0e6fd4)

**Comment by dikoutas** [comment]
@atsta ίσως να είναι το πρόβλημα που έχει παρατηρηθεί αρκετά συχνά, ας κάνουμε αν γίνεται ένα investigation, νομίζω να κάνουμε identification το πρόβλημα είναι σημαντικότερο από τη λύση.

**Comment by atsta** [comment]
@Vlefteris92  εάν κάνεις μία αναζήτηση που δεν εχει αποτελεσματα και μετά χρησιμοποιήσεις το μπρος-πισω του browser, δεν ανανανεώνεται η σελίδα παρόλο που πήγαμε πίσω. Γι'αυτό, εάν γράψω κάτι στην αναζήτηση που δε μου φέρνει αποτελέσματα, θα πρέπει να σβήσω το κείμενο αναζήτησης με backspace έτσι ώστε να ενημερωθούν τα αποτελέσματα. Το αντίστοιχο συμβαίνει και με τη σύνθετη αναζήτηση. Εάν φιλτράρω με κάτι και δε φέρει αποτελέσματα, πρέπει να πατήσω "Καθαρισμός φίλτρων" για να φέρει.
