### ISSUE TITLE
Newsletter Subscription - customization method bug

### ISSUE THREAD

**Issue by tpolitis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#444]
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/136069353/1c5ac71f-bdc8-4a34-8d65-cf4e230e6b52)

Στο _subscribeToNewsletter το callback που γυρίζει δεν περιέχει στοιχεία επιτυχίας ή αποτυχίας του call.

**Comment by dikoutas** [comment]
@atsta δε το έχει ζητήσει κανείς, είναι παρατήρηση του Θάνου, αλλά είναι πολύ reasonable και απλό.
