### ISSUE TITLE
Cannot display second image

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#445]
NOVART

Δεν εμφανίζεται η δεύτερη εικόνα.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/199b3426-d8d2-4c6c-88dc-7fbdecbaa733)
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/c48ce95e-37f6-40af-b0e7-688c32f7a9d7)

**Comment by dikoutas** [comment]
@atsta μάλλον είναι bug που προέκυψε στο τελευταίο theme update.

**Comment by atsta** [comment]
@Vlefteris92 λύθηκε. Θέλει update theme.
