### ISSUE TITLE
Terms & Conditions Page

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#446]
NOVART

Ζητάει να δημιουργηθεί μια σελίδα με κουμπιά επιλογής όπως παρακάτω και στο κάθε κουμπί θέλει να εμφανίζεται ένα κείμενο που μας έχει δώσει. Έχει Start ή Basic, δεν ξέρω γιατί έχει ενεργοποιηθεί το Standard προσωρινά μάλλον για κάποιο customization. Εάν είναι αποδεκτό να το υλοποιήσουμε, θα χρειαστούμε κόστος και χρόνο υλοποίησης.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/bb519e0e-85b5-44e9-8fc1-8f7b7d83f1aa)

**Comment by atsta** [comment]
Ισως μπορούμε να κάνουμε κάτι κοντά σε αυτό χρησιμοποιώντας το Layout component και προσθέτοντας TextWithImage components.
![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/23361503/e7d918bf-b012-4ad4-97e7-85fe06b3bb2c)

@dikoutas για ακριβές αντίγραφο με accordion areas οπως δειξανε θέλουμε customization, το οποίο δεν επιτρέπει το επίπεδο συνδρομής τους.

**Comment by dikoutas** [comment]
@Vlefteris92 @atsta πολύ σωστά, νομίζω ας περιμένουμε να γίνει συνενόηση για upgrade σε standard ή έστω customization module και μετά συζητάμε. Στην τελική να το κάνουμε και όπως είμαστε αλλά μόνο χρεώσιμα.
