### ISSUE TITLE
Quote order quantity step(platform Shopranos)

### ISSUE THREAD

**Issue by tpolitis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#449]
Τα controls στο Shopranos δεν σέβονται το βήμα παραγγελίας για τα quotes.

**Comment by dikoutas** [comment]
@atsta στο site τα βήματα του quote παίζουν σωστά, αλλά δεν παίζουν στην πλατφόρμα και μετά διαμαρτύρεται και το checkout αν αποδεχθεί την προσφορά ο πελάτης.
