### ISSUE TITLE
Orders on user profile

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#450]
Euronics

Πατώντας για εμφάνιση σε νέες παραγγελίες δεν εμφανίζει το popup

Το πρόβλημα είναι επαναλαμβανόμενο και δεν εμφανίζεται με κάποιο patern.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/116309750/6c3ef551-1078-4ac1-9e6d-5a5bd0470e8c)

**Comment by atsta** [comment]
@Vlefteris92 δώσε μου ένα παράδειγμα πελάτη, γιατί το δοκίμασα σε κάποιους και δεν βρήκα το πρόβλημα.

**Comment by dikoutas** [comment]
@atsta έχουμε κάποιο update πάνω σε αυτό;

**Comment by dikoutas** [comment]
@raniavch προσπάθησε να κάνεις κάποιο τεστ, μήπως βρούμε κάποιο pattern.

**Comment by spyroskaravanis** [comment]
Τι έγινε τελικά;

**Comment by Vlefteris92** [comment]
Το είδαμε και σήμερα και με τον Δημητρη μπροστά. Οι παραγγελίες που έρχονται από το B2B δεν μπορούν να γίνουν εμφάνιση από το κατάστημα. Οι παραγγελίες που είχαν περαστεί στο soft1 φαίνεται να εμφανίζονται. Το παράδειγμα που είδαμε μαζί ήταν στον λογαριασμό του καταστήματος «ΓΕΩΡΓΙΟΥ ΛΕΩΝΙΔΑΣ και ΣΙΑ ΕΕ»
