### ISSUE TITLE
Menu Bar Hiding

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#451]
Roma

Κατα την περιήγηση στη σελίδα θα ήταν χρήσιμο να μην χάνετε το menu  by default  η να  υπάρχει επιλογή.

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/703eaa2a-2e06-46dd-9fd5-54f11bd2a708)

**Comment by dikoutas** [comment]
@atsta αυτό νομίζω είναι καλό enhancement προιοντικά. Αφορά την alternative προβολή.

**Comment by atsta** [comment]
@dikoutas υποστηρίζεται στο νέο θέμα
