### ISSUE TITLE
Συσχετισμός Κατηγορίας Προϊόντων με Banner 

### ISSUE THREAD

**Issue by tpolitis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#452]
Ζήτησε η Prime δυνατότητα συσχετισμού προϊόντων βάσει κατηγορίας(αντί να τα δηλώνει ξεχωριστά σε ένα προς ένα) με banners στο additional content.

**Comment by atsta** [comment]
@dikoutas να το δούμε στο grooming

**Comment by dikoutas** [comment]
[like]  Dimitris Koutas reacted to your message:
________________________________

**Comment by dikoutas** [comment]
@atsta θα το δούμε στο grooming.

Η ανάγκη είναι να μπορώ να κάνω single out μια κατηγορία προιόντων ή brand ή τελος πάντων κάποια τέτοια συσχέτιση και μετά να μπορεί να γεμίσει το additional content μαζικά.
