### ISSUE TITLE
Relative Products from Soft1

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#453]
Πελάτης ΠΙTΟΣ,

Ο πελάτης χρησιμοποίει στο Soft1 Custom Πίνακα όπου αποθυηκέυει εξαρτήματα και  σχετικά προιόντα για μερικά είδη.
Θα ήταν χρήσιμο να μπορεί να τα εισάγει μέσω Connector αντι να τα περνάει manual.

**Comment by atsta** [comment]
@AlexandrosStypsianos θα υλοποιηθεί μέσα στο μήνα. Θα ενημερώσω εδώ σχετικά.

**Comment by dikoutas** [comment]
@atsta το θέλει και η Novart, μήπως βάλουμε ένα setting στον connector για να εισάγεις σχετικά "παρελκόμενα" προιόντα. Με την ίδια λογική ίσως που υπάρχει στην περιγραφή;; Θα ήταν πολύ καλό αν μπορούμε να κάνουμε κάτι τέτοιο!

**Comment by spyroskaravanis** [comment]
μπορει με custom
