### ISSUE TITLE
Sorting  Problem on Client Catalog

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#454]
Κατα την ταξινόμηση στη λίστα πελατών δεν λειτουργεί η ταξινόμηση κατα αλαφαβιτή σειρά.
Το συγκεκιρμνένο έχει παρατηρηθεί  γενικά στις εγκαταστάσεις.

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε
