### ISSUE TITLE
Auto user invitation

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#456]
Novart

Ενώ είναι ενεργή η επιλογή για αυτόματη πρόσκληση χρηστών, κατά τον συγχρονισμό πελατών δεν φεύγει πρόσκληση στο default mail αυτόματα.

**Comment by spyroskaravanis** [comment]
Να περαστεί από φανή αν ισχύει
