### ISSUE TITLE
Position(order) στα Blogs

### ISSUE THREAD

**Issue by tpolitis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#457]
Πάνω στα blog να ορίζουμε ένα position το οποίο θα καθορίζει την σειρά εμφάνισης όπως είναι και στα products.

**Comment by atsta** [comment]
@raniavch είναι Legit αυτο;

**Comment by raniavch** [comment]
το έψαξα στο shopify + bigcommerce, δεν βρήκα να έχουν σειρά εμφάνισης στα blogs.. μου φαίνεται όντως χρήσιμο αλλά low priority
