### ISSUE TITLE
Minimun Order QTY Problem 

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#460]
Στον πελάτη ΡΟΜΑ ΕΛΛΑΣ παρατηρήθηκε ότι στην καρτέλα του είδους στο Shopranos  δεν υπάρχει η δυνατότητα 
συμπλήρωσης ελάχιστης ποσότητας παραγγελίας,βήμα παρ, και προτεινόμενη με δεκαδικά ψηφία.
Στην προσθήκη στο καλάθι η λειτουργία παίζει κανονικά. 

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/83cfae10-902e-4af1-8534-8744fd7ca8fd)

![image](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/3610f0dc-db19-44a7-863f-65a4a8107f65)

**Comment by atsta** [comment]
@AlexandrosStypsianos λύθηκε
