### ISSUE TITLE
NOVART PDF

### ISSUE THREAD

**Issue by Vlefteris92** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#462]
Ο πελάτης ζητά να αλλάξει η διάταξη του PDF παραγγελίας σύμφωνα με το επισυναπτόμενο.
Τους έχουμε δώσει 5 ώρες χρέωση και τις έχουν αποδεχτεί.

[ΦΟΡΜΑ ΠΑΡΑΓΓΕΛΙΑΣ.docx](https://github.com/user-attachments/files/15911350/default.docx)

**Comment by dikoutas** [comment]
@tpolitis και αυτό σε παρακαλώ για τα έργα.
