### ISSUE TITLE
Double expenses on checkout

### ISSUE THREAD

**Issue by AlexandrosStypsianos** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#464]
Στον πελάτη Krannich 
εμφανίζονται διπλά τα έξοδα στο checkout.

Τα έξοδα στο σύνολο υπολογίζονται σωστά, το πρόβλημα ειναι θέμα εμφάνισης.

![Screenshot 2024-07-03 114824](https://github.com/Softone-Technologies-S-A/Shopranos-Issue-Tracker/assets/142010961/f5a98ac0-c6a9-422f-92fa-d3fba3e3ddb8)

@georgopoulosgianniss

**Comment by spyroskaravanis** [comment]
Μάλλον από soft1 έρχονται διπλά.
