### ISSUE TITLE
Regate

### ISSUE THREAD

**Issue by atzaferai** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#466]
Remove from OrderDetailItem --> CalculateOrderDetailOnPromotion (check candelli v171):
		vat_percent = 0;
		line_vat = 0;
		line_price = 0;
		line_total = 0;

Add customer_id while CheckIfInvoiceIsAlreadyCanceled XV_InvoiceHistoryActivity, XVPrintBusiness (check candelli v172)

**Comment by spyroskaravanis** [comment]
λάθος σημείο to issue δες το Μάνο μην χαθεί @mpergioudakis
