### ISSUE TITLE
Customization-Home page title

### ISSUE THREAD

**Issue by DimitraStav** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#5]
![image](https://user-images.githubusercontent.com/95525448/190107456-07899545-5561-4ace-8a0f-ab549ac22f49.png)
Στο customization στα layouts στο home page να μπει καποιος defualt τιτλος γιατι και ερχεται κενο στο content ->menu->header menu
![image](https://user-images.githubusercontent.com/95525448/190107958-78e3d58b-125f-4c42-8e4e-0e40157af796.png)

**Comment by spyroskaravanis** [comment]
Softone-Technologies-S-A/Shopranos-Issue-Tracker#7
