### ISSUE TITLE
Price Range φίλτρο αγνοεί την έκπτωση

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#50]
Αν επιλέξω minPrice 4 πχ και ένα προϊόν έκανε 4,80 και με έκπτωση είναι 3,47 θα εμφανιστεί που είναι λάθος
![image](https://user-images.githubusercontent.com/113907624/200513666-433cc0d2-57aa-44ac-8213-769a8d23837e.png)

**Comment by spyroskaravanis** [comment]
Η έκπτωση παίζει στην αρχική τιμή. Επειδή κάθε πελάτης έχει τα δικά του price policies.
