### ISSUE TITLE
Quantity Not Available Exception

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#51]
Ένα προϊόν που μάλλον τελείωσε το stock του παρέμεινε στο καλάθι μου και όταν πήγα στην ολοκλήρωση αγοράς, μου έβγαλε το παρακάτω. Δεν υπάρχει καμιά ενημέρωση για το ποιό είναι.

![image](https://user-images.githubusercontent.com/113907624/200818611-8f67b6ac-a602-47ce-9163-c35d6c4b1d0e.png)

**Comment by spyroskaravanis** [comment]
![image](https://user-images.githubusercontent.com/87171031/201092014-8c2acc5f-73ee-4d23-8625-9aecf7271f12.png)
