### ISSUE TITLE
Related errors

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#52]
Και στο default related products, εμφανίζει error το component και δεν παιζει
![image](https://user-images.githubusercontent.com/113907624/201868152-3a0b73d9-209b-4782-a6e7-702e401c2402.png)

**Comment by ploumis** [comment]
Είναι θέμα με το carousel πιστεύω

**Comment by clioli0s** [comment]
Είναι θέμα με το carousel. Δεν υπάρχουν related products και δεν ρεντάρεται το component λόγω ελέγχου και το carouselInitialization() δεν βρίσκει element για να δημιουργήσει το carousel. Σου έβαλα ένα null check για το element για να μην σκάει. Αν θες μπορείς να το χειριστείς και αλλιώς, πχ να μην καλείται το carouselInitialization() αν δεν υπάρχουν related.
