### ISSUE TITLE
Δεν μου δέχεται το custom cart component στο checkout page

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#54]
Βέβαια εκείνο το component αναγράφεται με τύπο checkout, το component στο cart ποιό είναι;

**Comment by ploumis** [comment]
Ουσιαστικά, στην σελίδα cart, έχω επιλέξει από το διαχειριστικό custom component με κλασεις δικες μου, αλλα μπροστά δεν το φορτώνει, έχει το default

**Comment by clioli0s** [comment]
Από ότι βλέπω κανονικά φορτώνεται το custom_cactus. Θες να μου στείλεις ένα screenshot ή να το δούμε με κάποιο Teams ?
