### ISSUE TITLE
Μετά από successful login, αντί να με πετάει αρχική ή έστω my-account, με αφήνει στο login page

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#55]
![image](https://user-images.githubusercontent.com/113907624/202122265-f670191c-d297-4425-9a55-eb1d41687ecb.png)

**Comment by clioli0s** [comment]
Δουλεύει σωστά από ότι βλέπω τώρα.
@ploumis δες το και εσύ και το κλείνουμε.
