### ISSUE TITLE
Electronics theme - pagination όταν αλλάζεις σελίδα σε αφήνει κάτω και δεν σε οδηγεί πάνω

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#59]

**Comment by clioli0s** [comment]
Δεν δούλευε το scrollTo να πάει top γιατί το body έχει overflow hidden.
Άλλαξα στο custom_cactus_final τον τρόπο που κάνει scroll.
Δεν έχω κάνει publish το theme.
