### ISSUE TITLE
Choose date

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#62]
όταν πατάς choose date στην καρτέλα πελάτη, σπάει η σελίδα με τα παρακάτω errors,
επιπλέον,
Default θέλουμε μόνο αυτού του μήνα και να έχουμε ένα calendar για να διαλέγουμε εύρος
![image](https://user-images.githubusercontent.com/113907624/203805735-6603796f-12bd-4296-bd86-9b769f1d147e.png)

**Comment by clioli0s** [comment]
@ploumis Φαίνεται ότι παίζει οκ, κάνε ένα hard refresh και πες μου
