### ISSUE TITLE
Στις παραγγελίες στην εμφάνιση, το link δεν δουλεύει

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#65]
Στο coffeelab το έφτιαξα τώρα, αλλά σε πήγαινε το link σε 'shop-single-v1.html'
Επιπλέον το alias δεν υπάρχει στο line object οπότε χρειάζεται να το πάρεις από αλλού. Σε περίπτωση που το προσθέσετε στο object το alias, θα ήταν βολικό να προστεθεί και image link
![image](https://user-images.githubusercontent.com/113907624/204810064-380ba509-ae27-45e0-8977-d37660904080.png)

**Comment by ploumis** [comment]
Το LINK του τίτλου προϊόντος στο modal**

**Comment by spyroskaravanis** [comment]
Μπορεί να γίνει μετά από αναζήτηση this._findProducts
