### ISSUE TITLE
Είναι δυνατό να κόβουμε το προϊόν από την προσθήκη στο καλάθι αν δεν έχει stock;

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#66]
Ή αν το quantity είναι μεγαλύτερο από το stock του. Είναι το πιο λογικό από να του πετάμε το μήνυμα στο checkout.

**Comment by spyroskaravanis** [comment]
Υπάρχει ακόμα το πρόβλημα;
