### ISSUE TITLE
Δεν μπορούμε να διαγράψουμε παραγγελίες στο διαχειριστικό

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#68]
Επιλέγουμε την παραγγελία και πατάμε διαγραφή και δεν γίνεται τίποτα.

**Comment by atsta** [comment]
@ploumis Επειδή η παραγγελία ενημερώνεται στο back office, μπορεί να γίνει διαγραφή παραγγελίας μόνο εφόσον ακυρωθεί πρώτα.

![cancel_order](https://user-images.githubusercontent.com/23361503/207011385-cdf9091a-eff5-40e2-bb1d-f610e0652212.png)

**Comment by atsta** [comment]
@ploumis  βάλαμε την επιλογή της μαζικής ακύρωσης για τα status παραγγελίας που δεν επιτρέπουν την άμεση διαγραφή 

![image](https://user-images.githubusercontent.com/23361503/214577494-b9e6b798-603a-4a2c-aa2c-2565ed3b9cf5.png)
