### ISSUE TITLE
Ειδος και κατηγορια-save

### ISSUE THREAD

**Issue by DimitraStav** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#7]
Οταν παω να προσθέσω σε ενα ειδος κατηγορια και κανω save δεν φαινεται η αλλαγη.
![image](https://user-images.githubusercontent.com/95525448/190113385-8758825d-da61-4034-b513-88bfae8b8392.png)

Φτιαχνοντας μια νεα κατηγορια το placeholder του τιτλου και του κωδικου ειναι ιδιο, και στα δυο γραφει category title.
![image](https://user-images.githubusercontent.com/95525448/190114685-3d2d0a7a-bd06-4561-b678-964d0ccb93bf.png)

**Comment by atsta** [comment]
Softone-Technologies-S-A/Shopranos-Issue-Tracker#7
