### ISSUE TITLE
Πληροφορία αν ο invited πελάτης έχει πατήσει το link και έχει ολοκληρώσει εγγραφή

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#73]
Θέλουμε να υπάρχει η πληροφορία ενός invited χρήστη στο σύστημα αν έχει προσθέσει κωδικό, δηλαδή έχει ολοκληρώσει εγγραφή

--- plhrofori mh register xristes

**Comment by PolysP** [comment]
Θα υλοιποιηθεί σε επόμενο release
