### ISSUE TITLE
Shopranos Orders

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#74]
1. Το sort στα orders newest -> oldest λειτουργεί ανάποδα
2. Να μπεί μια στήλη με την συνολική αξία της παραγγελίας και το CL του πελάτη.
3. Επίσης δεν είναι φαίνονται όλες, π.χ. από το Order 077 πάμε στο 104

**Comment by atsta** [comment]
@ploumis τα 1 και 2 έχουν ανέβει.
