### ISSUE TITLE
Backend Orders του customer pagination + view amount

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#76]
Όταν είσαι στην σελίδα ενός customer και οι παραγγελίες είναι > 10, αν πατήσεις 2η σελίδα ή να δείς 25/50/100 τότε εμφανίζει error
![image](https://user-images.githubusercontent.com/113907624/212336056-9537951d-5200-4cf6-b60b-8960bd647d26.png)

![image](https://user-images.githubusercontent.com/113907624/212335964-b99c06d3-fef1-4cf3-9cbf-f763ed674e0c.png)

**Comment by atsta** [comment]
@ploumis διορθώθηκε.
