### ISSUE TITLE
Reset Password δεν λειτουργεί

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#77]
Έρχεται κανονικά link, αλλά στην σελίδα για reset αφού συμπληρώσουμε τον νέο κωδικό 2 φορές, δεν δουλέεύει το κουμπί συνέχεια. Κάνει ajax χωρίς αποτέλεσμα.
![image](https://user-images.githubusercontent.com/113907624/213135959-c1588d26-6b09-42d4-9207-ce4310efbbb7.png)

**Comment by clioli0s** [comment]
Έχει γίνει μία διόρθωση αλλά χρειάζεται παρακολούθηση και δεν το κλείνω το issue.
@ploumis εάν συμβεί ξανά μας λες
