### ISSUE TITLE
Μετά την εγγραφή, στην είσοδο στο πεδίο email κάνει autocomplete το όνομα και μπερδεύει τους χρήστες

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#79]
Πολλοί χρήστες μπερδεύονται με το autocompleted ονομα στο πεδίο του email και θεωρούνε πως έχουν κληδωθεί από το σύστημα.
Αν είναι εύκολο να κάνει autocomplete με το email ή καθόλου.

**Comment by clioli0s** [comment]
@ploumis Στην σελίδα του Login κάνει autocomplete ? Αφορά το Eshop ή το διαχειριστικό ? Στείλε ένα screenshot αν μπορείς.

**Comment by ploumis** [comment]
Στο login του B2B Eshop. Αυτήν την στιγμή δοκίμασα με ένα invitation να το βγάλω screenshot αλλά δεν μου το κάνει. Παρόλα αυτά 100% το έχουμε δει σε 5 πελάτες. Αν τώρα δεν το κάνει γιατί το αφαιρέσατε τότε μπορείτε να το κλείσετε το ticket.

**Comment by clioli0s** [comment]
Δεν έχουμε αφαιρέσει κάτι. Υποθέτω ότι έχει να κάνει με ποιο browser μπαίνει κάποιος γιατί το autocomplete γίνεται συνήθως από το browser αναλόγως ποιον χρησιμοποιείς. Μπορείς να βάλεις στα input της φόρμας autocomplete="off" (κάπως έτσι γίνεται, δες το και εσύ) για να μην συμβαίνει.
