### ISSUE TITLE
Δεν μπορούμε να κάνουμε invite χρήστη στο shopranos που να έχει μόνο ρόλο Manage customers

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#82]
Όπως βλέπετε παρακάτω, δεν μπορούμε να του δώσουμε άλλο ρόλο εκτώς από admin
![image](https://user-images.githubusercontent.com/113907624/214011656-445ef095-f476-4e7c-9306-f081fef18001.png)

Επιπλέον στους ρόλους πατώντας add new role, μας εμφανίζει κενό popup
![image](https://user-images.githubusercontent.com/113907624/214012300-5709e1cd-04eb-452c-828d-cb4a96b7ea16.png)

**Comment by atsta** [comment]
@ploumis διορθώθηκε
