### ISSUE TITLE
Upload Files με μορφή SXNN και δεν τις εμφανίζει.

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#83]
Ανεβάζω φωτογραφίες στο Gallery με μορφή SXNN και δεν τις εμφανίζει στο front. Στο gallery τις κρατάει σαν αρχεία. Επίσης, δεν τις βάζω στο Central αλλά στο GR. Παράδειγμα ονόματος αρχείου (00173110_00, 00173110_01). Για την ώρα θα δοκιμάσω να τις ανεβάζω εσωτερικά στο κωδικό.

**Comment by spyroskaravanis** [comment]
Η μάσκα ήταν S.

**Comment by KonstantinaTsir** [comment]
Ευχαριστούμε! It works now!
