### ISSUE TITLE
Collections Request Backend

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#84]
Θα μπορούσαμε στα manual collections να εμφανίζεται και το sku των προϊόντων που τοποθετούμε; 

Έτσι ώστε να μπορεί να γίνει εύκολα το ordering στο διαχειριστικό γιατί τώρα φέρνει μόνο περιγραφές προϊόντων;

**Comment by PolysP** [comment]
ΟΠΟΥ ΚΑΛΟΥΜΕ ΠΕΛΑΤΗ ή ΕΙΔΟΣ ΘΑ ΠΡΕΠΕΙ ΝΑ ΥΠΑΡΧΕΙ ΚΑΙ Ο ΚΩΔΙΚΟΣ
