### ISSUE TITLE
Reply Email

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#86]
Στα Contact Forms, να υπάρχει η δυνατότητα για reply email profile.

Πχ. Όταν συμπληρώνουμε φόρμα register & κάνουμε submit, να πηγαίνει ένα mail επιβεβαίωσης.

**Comment by spyroskaravanis** [comment]
Στην φόρμα επικοινωνίας να δοθεί η δυνατότητα για auto reply με email template.
