### ISSUE TITLE
Products Global Subsidiaries Issue

### ISSUE THREAD

**Issue by ThanosPolitis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#89]
Βάζοντας φωτογραφίες στο φάκελο products_global της central εταιρείας, δεν περνάνε στον αντίστοιχο φάκελο της εκάστοτε εταιρείας-παιδί.

**Comment by atsta** [comment]
@ThanosPolitis δοκίμασα να ανεβάσω μία φωτογραφία στο products_global στη Central και ανέβηκε κανονικά στις θυγατρικές. 
Δοκίμασε ξανά και αν υπάρχει ακόμα θέμα, να το δούμε συγκεκριμένα.
