### ISSUE TITLE
Matching φωτογραφίες με προϊόν βάση sku

### ISSUE THREAD

**Issue by ploumis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#92]
Παρατηρήσαμε ότι το matching των φωτογραφιών για προϊόν με κωδικό πχ ARG-DEL T, δεν κάνουν αυτόματο match με τις φωτογραφίες με κωδικό ARG-DEL T_00 μάλλον γιατί υπάρχει κενό.

Σε άλλα προϊόντα που δεν υπάρχει κενό γίνεται η σύνδεση κανονικά όταν τις ανεβάζουμε, αλλά σε αυτά που είχαν κενό δεν έγινε.

προϊόν που παρατηρήθηκε αυτό:
ARG-DEL-13380 T
ARG-DEL-13380 T_00 (η φωτογραφία)

**Comment by atsta** [comment]
@ploumis λύθηκε.
