### ISSUE TITLE
Media Gallery Photos Overwrite Issue

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#93]
Θα θέλαμε να γίνεται overwrite των παλιών φωτογραφίων από τις καινούργιες.

**Comment by atsta** [comment]
@KonstantinaTsir στις ρυθμίσεις του Media Gallery, μπορείτε να επιλέξετε την επιλογή **Παράλειψη**

![image](https://user-images.githubusercontent.com/23361503/219574080-91314437-f6d4-4514-89fc-66a5cc80c435.png)

Εφόσον ανεβάσετε εικόνα με την ίδια ονομασία, θα αντικαταστήσει την παλιά στο προϊόν. 
Αυτό σας καλύπτει ή εννοείτε κάτι διαφορετικό;

**Comment by KonstantinaTsir** [comment]
Τώρα το είδα αυτό, ευχαριστώ πολύ @atsta. Θα κάνω μία δοκιμή ξανά & αν προκύψει κάτι ενημερώνω ξανά.
