### ISSUE TITLE
Duplicate Images on Product - overwrite issue

### ISSUE THREAD

**Issue by ThanosPolitis** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#97]
Φαίνεται πως το overwrite option στο media gallery δεν λειτουργεί σωστά καθώς στο ανέβασμα φωτογραφιών με ίδιο όνομα δεν γίνεται overwrite πάνω στο προϊόν αλλά κρατάει και όλες τις φωτογραφίες κι ας έχουν κοινό όνομα.

**Comment by atsta** [comment]
@ThanosPolitis είναι η ρύθμιση στο Media gallery στην επιλογή overwrite;
θα μπορούσες να μας δώσεις το sku ενός προϊόντος που έχει αυτό το θέμα καθώς και το αρχείο που ανεβάζετε για να γίνει overwrite;

**Comment by KonstantinaTsir** [comment]
Αθηνά, δοκίμασα για δύο sku να περάσω φωτογραφίες που ήδη υπήρχαν live και έκανε overwrite (αλλάζει και την ημερομηνία του uploading updated). Δεν γνωρίζω αν διορθώσατε κάτι.

Αν παρατηρήσω κάτι άλλο θα σε ενημερώσω εδώ.

**Comment by atsta** [comment]
@KonstantinaTsir οκ
