### ISSUE TITLE
Brands - Δεν κρατάει το text

### ISSUE THREAD

**Issue by KonstantinaTsir** [Softone-Technologies-S-A/Shopranos-Issue-Tracker#98]
Στα product settings->brands, δεν κρατάει το διαχειριστικό τις μεταφράσεις των Ελληνικών & Αγγλικών. Διατηρεί μόνο τα Default κείμενα.

**Comment by atsta** [comment]
@KonstantinaTsir το δοκίμασα και φαίνεται να λειτουργεί. 
Θα μπορούσες να μου πεις έναν κωδικό brand που το παρατήρησες;

**Comment by KonstantinaTsir** [comment]
Βεβαίως! Για παράδειγμα πήγα τώρα να προσθέσω GR σε Fujitsu και δεν τα κράτησε.

**Comment by atsta** [comment]
@KonstantinaTsir διορθώθηκε. Εάν είχατε πολυγλωσσικές περιγραφές ήδη σε κάποια brands, δεν έχουν χαθεί.

**Comment by KonstantinaTsir** [comment]
Σε ευχαριστώ πολύ @atsta!
